### ISSUE TITLE
Unknown argument 'loc'.

### ISSUE THREAD

**Issue by meling** [zsh-users/antigen#100]
On Mac OS X Yosemite I get:
```
% zsh --version
zsh 5.0.5 (x86_64-apple-darwin14.0)
% env | grep ANTI 
ANTIGEN_DEFAULT_REPO_URL=https://github.com/robbyrussell/oh-my-zsh.git
% antigen use oh-my-zsh
Unknown argument 'loc'.
% antigen theme robbyrussell
Unknown argument 'loc'.
```

All other antigen command seems to work fine. I suspect that the problem with these commands is what is causing my theme to look different from my previous use of oh-my-zsh, and also the cursor is sometimes misplaced. 

I did some quick debugging and it seems like this is the line that causes the `Unknown argument`:

```
    eval "$(-antigen-parse-args \
            'url?, loc? ; branch:?, no-local-clone?, btype:?' \
            "$@")"
```

I've not been digging deeper into the `antigen-parse-args()` function yet. I would appreciate any help with this. Thanks!

**Comment by JonathanReeve** [comment]
I'm getting these same errors on Ubuntu 14.10. 

    > zsh --version                                                                                     
    zsh 5.0.2 (x86_64-pc-linux-gnu)

    > env | grep ANTI                                                                                  
    ANTIGEN_DEFAULT_REPO_URL=https://github.com/robbyrussell/oh-my-zsh.git

**Comment by desyncr** [comment]
Any update on this @JonathanReeve @meling ?

**Comment by meling** [comment]
Nope, not on my end. I gave up antigen and went back to oh-my-zsh.

**Comment by desyncr** [comment]
I seems I can't reproduce this. If somebody can reproduce it consistently feel free to re-open it.

**Comment by JonathanReeve** [comment]
Not with me either. I switched to zgen.
