### ISSUE TITLE
Call for help

### ISSUE THREAD

**Issue by sharat87** [zsh-users/antigen#103]
As you all might have noticed, there are long awaiting issues and pull requests that need to be dealt with. I am sorry I could't respond quickly enough, but it has been hard for me to find the time. I hoped I'd find the time for this project, but could not. So, instead of keeping it in the dark, I'm putting this message out.

Any contributors interested in taking this project forward can join in the zsh-users group and start moving it. I think being in the group gives you write permission to the repo. If someone is up for becoming the new maintainer, we can discuss that out too.

I love this project. I thank everyone for showing your love and spreading the word. I can't thank enough those who've reported issues and submitted PR's and bore with me to make antigen even better.

This isn't a good bye. This is a call for a helping hand. Thank you.

**Comment by desyncr** [comment]
Count on me to keep the issue tracker active. I don't know much of antigen code base so I can't be that helpful in that regard but I'll keep an eye and try to help.

**Comment by ZeroKnight** [comment]
Just stumbled upon this project and I really like the idea. Currently using OMZ and quite like it, and have indeed learned a fair deal about zsh because of it, but the plugin setup is a bit of a mess...

I'll help out in any way I can. Once I have time to familiarize myself with antigen I'll definitely try and help improve it :)

**Comment by sharat87** [comment]
Thank you people! Thank you so much @desyncr, any help is appreciated :)

**Comment by sharat87** [comment]
Hey @nicoulaj, can you add @desyncr to the @zsh-users group so he has write permissions to the antigen project please? If you're not the right person for this, please advise. Thank you.

**Comment by nicoulaj** [comment]
done

**Comment by desyncr** [comment]
Thanks a lot! @sharat87 @nicoulaj

**Comment by desyncr** [comment]
I'm closing this in favor of https://github.com/zsh-users/antigen/issues/198
