### ISSUE TITLE
AntiGen Themes not working

### ISSUE THREAD

**Issue by firegore** [zsh-users/antigen#105]
installed AntiGen via ArchLinuxs AUR and via Github here, everything works fine exept the Themes, AntiGen just doesnt care, it downloads the Theme, but nothing visible changes, even after opening a new Session, tried over SSH and Local Console
![image](https://cloud.githubusercontent.com/assets/1130283/5688013/e13024e4-9852-11e4-93b9-c74de5be08aa.png)

EDIT: The Bundles are working, and nothing should modify the PS1 Var, fresh ZSH 5.0.7 installation on ArchLinux

**Comment by firegore** [comment]
Nevermind, got it fixed

**Comment by stardiviner** [comment]
My theme is not working too. and including every theme in oh-my-zsh. 
And I'm also using Arch Linux, with Zsh 5.0.7.

@firegore do you know how to fix it?

**Comment by firegore** [comment]
@stardiviner did you have grml-zsh-config installed?

**Comment by stardiviner** [comment]
you're right, after remove the package `grml-zsh-config`, my problem is solved. weird. What does the grml-zsh-config did?

**Comment by firegore** [comment]
@stardiviner it replaces the PS1 Variable, i have it installed, you just need to go into the: /etc/zsh/zshrc and delete the following line:

should be Line 2346:
grml_prompt_addto PS1 "${left_items[@]}"

Remember to delete the Line after every Update of the Package

then the Themes will work :)

**Comment by stardiviner** [comment]
Why grml will replace this? should we post a issue to grml? I deleted the grml package.
@firegore and Thanks.

**Comment by firegore** [comment]
It does this because the PS1 Variable is need e.g. for themes, the PS1 
Var represents the Shell of your Console ([hostname#] or similar)

i dont think it's a Bug, both edit the ZSH Theme, so they are not that 
compatible.

i like the grml-zsh-config because it has one Feature i dont remember 
now, but i wanted it so badly, that on every grml update, i edit the 
config file on all of my Servers^^
