### ISSUE TITLE
antigen bundle and -antigen-ensure-repo taking too much time on cygwin

### ISSUE THREAD

**Issue by 5paceToast** [zsh-users/antigen#106]
zprof of the issue: http://termbin.com/gjt0
I tried unhashing -antigen-ensure-repo and making it null, resulting in http://termbin.com/vaar
Either way, it took ~3 seconds to launch each.

my zshrc may be found here: http://termbin.com/cfxn
as you can see, I load very few modules

This setup works fine on FBSD and Gentoo, making me thing this is a cygwin-specific issue, but I've no idea what it is specifically.

**Comment by desyncr** [comment]
This is a know issue being take care of at #119 #132 #141. I'm closing this.
