### ISSUE TITLE
Please add a note about supported versions of zsh to the README

### ISSUE THREAD

**Issue by offbyone** [zsh-users/antigen#107]
I don't know what the minimum version is, and as someone who isn't a zsh expert I'm not sure what it would even be, so I'm hoping to see some note in the doc about a minimum working version *for the antigen framework*. 

Thanks!

**Comment by offbyone** [comment]
FYI, with some docker mucking about, I think I've confirmed that <5 doesn't work properly (it has some issues in the code that reports on bundle updating) but 4.2.0 mostly works.

**Comment by desyncr** [comment]
Antigen is tested against zsh 4.3 and 5.0. Should work on  zsh >= 4.3,  5.x
