### ISSUE TITLE
Prezto prompt themes

### ISSUE THREAD

**Issue by hostmaster** [zsh-users/antigen#108]
I really like prezto's default [promt](https://github.com/sorin-ionescu/prezto/tree/master/modules/prompt) theme [sorin](https://github.com/sorin-ionescu/prezto/blob/master/modules/prompt/functions/prompt_sorin_setup) but unfortunatly have not been able to enable it with antigen. Is it possible to enable prezto themes ? 

I tried
````
    antigen bundle sorin-ionescu/prezto modules/prompt
````
but it just does not work

**Comment by pearofducks** [comment]
I'd think a change in the theme files from prezto is needed. Quite a lot of prezto specific functionality is defined, and antigen tends to be closer to stock zsh.

**Comment by gerrywastaken** [comment]
@hostmaster Yeah I tried the exact same command. :(

I love how it reduces directories other than the current down to one character. I wish that were possible with antigen.

**Comment by desyncr** [comment]
I belive this is the issue. https://github.com/sorin-ionescu/prezto/pull/713.
