### ISSUE TITLE
Further document how to use Antigen within a git repo

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [zsh-users/antigen#111]
The README implies Antigen is designed to work with a versioned configuration repository (‘[dotfiles repo](https://dotfiles.github.io).’ However, for the life of me, I can't figure out how to get Antigen to *just load* a ZSH plugin, instead of trying to download, install, update, manage, suckle, and homeschool the damn thing. :P

The README needs a little more explanation of how one gets Antigen to work with a [dotfiles-repo full of submoduled zsh modules](https://github.com/ELLIOTTCABLE/System/tree/Master/Dotfiles/vim/bundle), in a way similar to the usual usage of its' namesake, Pathogen. I can't be the only newcomer puzzled by this. (=

**Comment by desyncr** [comment]
I don't think antigen `bundle` command supports a single repo with multiple plugins. Dunno if, as with themes, you can specify a path altogether with a repo and branch.

**Comment by desyncr** [comment]
This issue is old. I'm closing this for now.

If you have a suggestion on how to achieve a better documentation on your particular issue feel free to re-open and share your ideas.
