### ISSUE TITLE
tty command not working inside plugins

### ISSUE THREAD

**Issue by dan-santana** [zsh-users/antigen#114]
I'm not sure why this is happening, but the `tty` command seems unable to give the correct output when running inside a plugin.

I was checking the source code, and it looks like that the issue is on the [`antigen-bundles`](https://github.com/zsh-users/antigen/blob/30098c1d99/antigen.zsh#L100) function, but I'm really not sure why this happens.

To reproduce this, try to use the [gpg-agent](https://github.com/robbyrussell/oh-my-zsh/blob/e55c715508/plugins/gpg-agent/gpg-agent.plugin.zsh#L41) plugin, which [exports the `tty` output inside `$GPG_TTY`](https://github.com/robbyrussell/oh-my-zsh/blob/e55c715508/plugins/gpg-agent/gpg-agent.plugin.zsh#L41). If used like this:

```
antigen use oh-my-zsh
antigen bundles <<EOBUNDLES
gpg-agent
EOBUNDLES
```

...the `GPG_TTY` becomes `not a tty`, while if used in this way:
```
antigen use oh-my-zsh
antigen bundle gpg-agent
```

... the variable is set as expected.

**Comment by desyncr** [comment]
A tty won't be allocated for `antigen bundles` because it's reading from _stdin_. You have to use `antigen bundle` for _gpg-agent_ plugin.
