### ISSUE TITLE
Some oh-my-zsh themes don't work properly

### ISSUE THREAD

**Issue by hobarrera** [zsh-users/antigen#117]
Using

```
$ cat .zshrc
source tmp/antigen.zsh
antigen use oh-my-zsh
antigen theme avit
```

Results in a broken theme: `pwd` is not show properly (it *is* shown when loading the theme via oh-my-zsh directly), and git status is only shown depending on loaded modules (I haven't been able to narrow down this perfectly).

I'm mentioning a specific theme since I noticed that some others work perfectly.

**Comment by HeroCC** [comment]
I was having some troubles with my custom theme that I wasn't having with oh-my-zsh in Antigen and I fixed mine and yours by removing the 'local' in front of the variables. Try copying the theme to a custom directory (to prevent updates), setting Antigen to use that theme, and removing the 'local' in front of the variable names.

Example:
```
local _current_dir="%{$fg[blue]%}%3~%{$reset_color%} "
local _return_status="%{$fg[red]%}%(?..⍉)%{$reset_color%}"
local _hist_no="%{$fg[grey]%}%h%{$reset_color%}" 
```
Should be:
```
_current_dir="%{$fg[blue]%}%3~%{$reset_color%} "
_return_status="%{$fg[red]%}%(?..⍉)%{$reset_color%}"
_hist_no="%{$fg[grey]%}%h%{$reset_color%}"
```

**Comment by desyncr** [comment]
Following issue at https://github.com/zsh-users/antigen/issues/122.
