### ISSUE TITLE
Cache for faster start-time

### ISSUE THREAD

**Issue by ijcd** [zsh-users/antigen#119]
Antigen does work each time to make sure your modules are up to date. I have a work around that allows you to cache things similar to how zgen does it (I created this last January before zgen exisited, I think...)

  https://github.com/ijcd/dotfiles/blob/antigen/antigen/antigen_demo.zsh

Would it be worthwhile to add some variation of this to antigen?

**Comment by HeroCC** [comment]
Please, I love antigen but the startup time takes much longer than it did without.

**Comment by desyncr** [comment]
:+1: Would love to have a faster start up time.

**Comment by dasJ** [comment]
:+1:

**Comment by desyncr** [comment]
Work in being done at #129 #132 #141. I'm closing this for now.
