### ISSUE TITLE
Themes don't support local variables

### ISSUE THREAD

**Issue by HeroCC** [zsh-users/antigen#122]
An example can be found in #117, antigen doesn't like using local variables in themes. Examples:
[![Gyazo](http://i.gyazo.com/e568d43d1831f627dc6af21215414ec7.png)](http://gyazo.com/e568d43d1831f627dc6af21215414ec7) 
uses local variables. Removing the local:
[![Gyazo](http://i.gyazo.com/60998d6f87ea8c3826b2bc7f950cb200.png)](http://gyazo.com/60998d6f87ea8c3826b2bc7f950cb200)

As you can see, removing the local results in PWD and others to be displayed. In Oh-My-ZSH, this theme works fine unmodified. I will search for more examples, feel free to comment if you find more.

**Comment by desyncr** [comment]
Fix will be available in [1.2.1](https://github.com/zsh-users/antigen/milestone/10) release. Currently in `next`/`develop`.
