### ISSUE TITLE
Does Antigen work with Zsh 5.0.8?

### ISSUE THREAD

**Issue by sheldond** [zsh-users/antigen#130]
Hello!

Today I upgraded zsh to 5.0.8, via homebrew on osx 10.10.3. After the upgrade my autocomplete is not working anywhere, not even for built in commands.

For example, if I type "c" and then press tab nothing happens. I expected zsh to say something like "zsh: do you wish to see all 164 possibilities (15 lines)?".

Here is a minimal .zshrc:
```
#!/bin/zsh
source "$HOME/.dotfiles/repos/antigen/antigen.zsh"
antigen apply
```

Without antigen everything is fine. My antigen clone is up to date with master.

Thanks!

**Comment by desyncr** [comment]
Running on 5.0.7 and latest master and works fine. Did you checked the [change log](https://github.com/zsh-users/zsh/blob/master/NEWS)? May be there is a clue.

**Comment by sheldond** [comment]
Good idea, no changes jump out to me as related to completion, but I'm also not too familiar with Antigen yet. 

Perhaps we can wait to see if someone else on 5.0.8 can confirm the issue, or we may find it's just me.

**Comment by desyncr** [comment]
I'll later on update to 5.0.8 and see if the issue persists. Given the version number I think there should not be any breaking changes, but we'll see.

**Comment by forivall** [comment]
I'm on 5.0.8 on Arch Linux and it works fine.

**Comment by desyncr** [comment]
Can confirm running zsh 5.0.8 (x86_64-redhat-linux-gnu) just fine.

**Comment by sheldond** [comment]
Thanks! The issue persists for me, deleting .zcompdump has no effect. Perhaps the issue is related to osx?

**Comment by sheldond** [comment]
The issue turned out to be related to file permissions, I ran `compaudit` to find "insecure directories" and then setup a new "zsh-users" user group with permissions on these directories.

**Comment by desyncr** [comment]
Interesting. Thanks for the info.
