### ISSUE TITLE
Plugin repo names are strange

### ISSUE THREAD

**Issue by j-walker23** [zsh-users/antigen#131]
Hey, cool stuff. Just starting out with this. Thank you!

The repos in `.antigen` look like they were not formatted correctly. Names look like this.
`https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh`.

Is that a bug or on purpose?

**Comment by desyncr** [comment]
Hey there @j-walker23 hope you'll find antigen useful. Feel free to ask questions on the issue tracker and participate in the discussions if you feel like it.

Responding to your question. It's an intended behavior. Repository folders are escaped that way to avoid issues with path and files names with characters like ':', '/' and so on.

Hope that'd help you.

**Comment by j-walker23** [comment]
Perfect, thank you. I just wanted to make sure i didn't have something setup wrong.
