### ISSUE TITLE
git plugin doesn't seem to work

### ISSUE THREAD

**Issue by JikkuJose** [zsh-users/antigen#134]
I have refactored my zshrc and added antigen to manage my plugins, everything works well except the git plugin. My theme typically shows the git status but know it doesn't. Can you please review my [zshrc](http://pastebin.com/v7hP5Dkj) and let me know if I configured antigen properly?

**Comment by desyncr** [comment]
'antigen theme'  must be placed before 'antigen apply'.

Hope that helps.

**Comment by JikkuJose** [comment]
Na it doesn't work. I purposefully put it outside.

**Comment by HeroCC** [comment]
This may not be the problem but: if you use antigen you should use "antigen use oh-my-zsh" and not source it directly. It looks you are executing both, try removing line 26.

**Comment by JikkuJose** [comment]
I had tried it, but there was no use. Surprisingly it works with the same file at home computer but not in office. By removing the sourcing of [.oh-my-zsh/oh-my-zsh.sh](http://pastebin.com/Tfy1uC5s) file it stops working at home too.

**Comment by JikkuJose** [comment]
Seems its the problem with my specific theme - jiks in [themes repo](http://github.com/JikkuJose/themes)!
