### ISSUE TITLE
Load a theme from local path

### ISSUE THREAD

**Issue by ajpaulson** [zsh-users/antigen#135]
Bundles can be loaded from local path instead of being cloned from a repo - can this be added in for themes?

**Comment by desyncr** [comment]
Yes you can, although it's hackish. For example you can:

    antigen bundle /home/user/Projects/zsh-syntax-hl --loc=zsh-syntax-highlighting.plugin.zsh --no-local-clone


Being '/home/user/Projects/zsh-syntax-hl' a local clone of zsh-users/zsh-syntax-highlighting plugin.

Hope that helps!

**Comment by ajpaulson** [comment]
That is what I was talking about as the current method for local bundles - I am asking about a similar method for themes - at the moment I have a theme locally that I want to use without putting it under a git repo or gist

**Comment by desyncr** [comment]
It's the same thing:

    antigen theme /home/user/Projects/powerlevel9k --loc=powerlevel9k --no-local-clone

**Comment by ajpaulson** [comment]
ahh thanks!

**Comment by HarvMarv** [comment]
Is this still working? I get errors using this method with a theme file which would work with omz.
