### ISSUE TITLE
The `-antigen-use-prezto` function silently affects how Zsh loads dotfiles

### ISSUE THREAD

**Issue by gwerbin** [zsh-users/antigen#137]
Prezto, unfortunately, does not provide an option to change its own dot directory. So I see why, to get it to work inside Antigen, the function `-antigen-use-prezto` does

    export ZDOTDIR=$ADOTDIR/repos

Without it, `pmodload` would look for Prezto modules in `~/.zprezto` instead of `~/.antigen/repos/.zprezto` and therefore would fail.

The problem is that `ZDOTDIR` is used by Zsh itself to determine where its startup/login/logout files are. For an example of what can happen, try this:

    # assuming $ZDOTDIR is unset initially, which is the default
    echo 'echo "this should run on login"' > ~/.zlogin
    echo 'echo "this should not run on login"' > ~/.antigen/repos/.zlogin
    source antigen.zsh
    antigen use prezto
    zsh --login

You'll notice that the correct file is ignored, and the stray file is run in its place.

An additional wrinkle is that a few of the Prezto modules also use `ZDOTDIR`, e.g. for [locating `HISTFILE`](https://github.com/sorin-ionescu/prezto/blob/master/modules/history/init.zsh#L13), and these probably should be in `~` as intended, and not in `~/.antigen/repos`. In fact, it seems like `pmodload` is the _only_ place where `ZDOTDIR` needs to be changed.

I've raised an issue with Prezto (sorin-ionescu/prezto/issues/920) about implementing some kind of `PDOTDIR` parameter. But in the meantime, maybe it wouldn't be a bad idea to re-implement `pmodload` on the Antigen side. If that seems like something you all would want to do, I can go ahead with a pull request to show you what I have in mind.

Also, in the current version, the line `ZDOTDIR=$ADOTDIR/repos/` should be `ZDOTDIR=$ADOTDIR/repos` to avoid ending up with double slashes.

**Comment by desyncr** [comment]
As noted, this is an upstream issue. Anything we can do to antigen are mostly hacks to make it work.
At least from the top of my mind I can't think a non-hacky way to solve it.

If you got an idea hack away and send your PR :)

**Comment by trusktr** [comment]
Here's what I did to st up Prezto. I changed the -antigen-use-prezto function to this:

```zsh
-antigen-use-prezto () {
    export ZDOTDIR=$ADOTDIR/repos
    antigen-bundle sorin-ionescu/prezto
}
```

It sets ZDOTDIR first which fixes some problems inside prezto when prezto isn't running from it's intended location (cc: @sorin-ionescu Please, we need these solved in one go: https://github.com/sorin-ionescu/prezto/issues/920, https://github.com/sorin-ionescu/prezto/pull/761, https://github.com/sorin-ionescu/prezto/pull/271, https://github.com/sorin-ionescu/prezto/issues/1025, https://github.com/sorin-ionescu/prezto/pull/791, basically make sure a new variable PDOTDIR based on ZDOTDIR is used everywhere).

Then I linked `~/.zshrc` to `~/.antigen/repos/.zshrc` and linked all `~/.antigen/repos/.z*` files to the respective ones in `~/.antigen/repos/.zprezto/runcoms/`.

After that, the only thing left to get prezto working is to put this in `.zshrc`:

```zsh
    source ~/path/to/antigen.zsh
    antigen use prezto
    antigen apply
```

**Comment by trusktr** [comment]
If antigen is doing `export ZDOTDIR=$ADOTDIR/repos` (which defeats the purpose of doing `antigen use prezto` because the expectation of `antigen use prezto` is that prezto will simply work without further tweaking and not having to compensate for a modified ZDOTDIR), the README may as well simply tell the user to set `ZDOTDIR` to `/path/to/antigen/repos` manually, and how to act accordingly, by moving all `~/.z*` files to the new directory (or linking to them).

**Comment by desyncr** [comment]
Done in v1.1.0.
