### ISSUE TITLE
Issue installing Antigen

### ISSUE THREAD

**Issue by astralscott** [zsh-users/antigen#142]
Hey guys, we are trying to install antigen, but having some issues.

When I run source antigen.zsh, we get these errors:

```
-bash: local: can only be used in a function
dirname: illegal option -- b
usage: dirname path
-bash: local: can only be used in a function
-bash: antigen.zsh: line 296: syntax error near unexpected token `('
-bash: antigen.zsh: line 296: `            for script ($location/*.zsh(N)) { source "$script" }'
```

We have the latest npm installed and node, but can't seem to get passed these errors which seem to be in the antigen.zsh file.

Any ideas?

Thank you!

**Comment by mpphilli** [comment]
Hi,

It looks like you are sourcing antigen.zsh from a bash shell. Make sure you are in zsh before doing the source.

MIKE

**Comment by desyncr** [comment]
Antigen is [zsh](http://www.zsh.org/) based. As I see in these error messages you're trying to run Antigen on bash. That's not possible and out of the scope of Antigen.

npm and node are not related to antigen or zsh at all.

Try 'apt-get install zsh' (or yum install zsh or similar) then log in in that shell and try the [installation/usage steps](https://github.com/zsh-users/antigen) again.
