### ISSUE TITLE
Have to run `source ~/antigen.zsh` every time I open the terminal?

### ISSUE THREAD

**Issue by Voyga** [zsh-users/antigen#145]
I have to source it every time I open the terminal window. And the plugins I added will disappear. How to fix this?

**Comment by desyncr** [comment]
The READ me explains it a [bit](https://github.com/zsh-users/antigen#usage). In your .zshrc (or wherever you put your configs) after you source antigen you have to use [antigen bundle](https://github.com/zsh-users/antigen#antigen-bundle) or [antigen bundles](https://github.com/zsh-users/antigen#antigen-bundles) to load your bundles.


A basic config would look like:

    source ~/antigen.zsh
    antigen use oh-my-zsh

    antigen bundles <<EOBUNDLES
        jimhester/per-directory-history
        zsh-users/zsh-syntax-highlighting
    EOBUNDLES

    antigen theme robbyrussell

    antigen apply

See examples [here](https://github.com/zsh-users/antigen/wiki/In-the-wild).

**Comment by Voyga** [comment]
Thanks. It could work.
