### ISSUE TITLE
Bug when using themes with right prompt 

### ISSUE THREAD

**Issue by JakubMatejka** [zsh-users/antigen#148]
The prompt is shifted three places left (and so is rewriting last three characters of the prompt) when I use any theme having some info on the right. See the screenshot (with theunraveler theme):

![zsh_theme_bug](https://cloud.githubusercontent.com/assets/215660/10427518/a973963c-70ea-11e5-91df-1056c4ebe390.png)

**Comment by desyncr** [comment]
![a](https://cloud.githubusercontent.com/assets/1857707/10456978/680b39e2-719a-11e5-9af5-b15ca4168776.png)

Works for me with theunraveler theme. zsh version? terminal?

**Comment by JakubMatejka** [comment]
The problem is probably in iTerm 2 app (on Mac) because in standard Mac Terminal app it looks ok. Sorry for false alarm. ;o)

**Comment by desyncr** [comment]
If it's a problem it should not be closed.

**Comment by JakubMatejka** [comment]
Well, I'm not sure if this is the best place where it should be reported. I tried also with oh-my-zsh and there is this problem too. Shouldn't I report it rather there since antigen uses it's templates?

**Comment by desyncr** [comment]
In that case, yes, you're right. It'd be better to report to the oh-my-zsh team about it.

**Comment by JakubMatejka** [comment]
Ok, will do. Anyway, thanks for your assistance.
