### ISSUE TITLE
Feature request: antigen individual files at root level

### ISSUE THREAD

**Issue by milieu** [zsh-users/antigen#152]
> A subtle aspect of this is that you can tell antigen to grab just about anything from anyone's dotfiles repo, as long as it is in a directory under any repo on github. -- [README.mkd](https://github.com/zsh-users/antigen/blob/master/README.mkd)

It would be nice if this 'subtle aspect' was expanded to enable something like:

```zsh
antigen bundles <<EOBUNDLES
  friend/dotfiles .aliases       # aliases for working on a common project
  company/dotfiles .env .aliases # environment & aliases specific for work
EOBUNDLES
```

If my use case doesn't make sense or if there is a simpler way of solving my problem (short of having everyone copy-paste from everybody else's dotfiles, which antigen is trying to solve, no?), please let me know.

Thank you!

**Comment by desyncr** [comment]
I think the use case is too narrow and there are bigger issues (performance, prezto support) to consider  implementing this, unless there is anybody interested in taking a chance and implement this feature.

I'm closing this now for the time being.
