### ISSUE TITLE
[feature request] Dependency management.

### ISSUE THREAD

**Issue by trusktr** [zsh-users/antigen#153]
Perhaps adopt [ied](https://github.com/alexanderGugel/ied), start up a self-hosted (NPM) registry (but all the packages would contain shell code instead of JavaScript), and then you'll have instant dependency management. Then we'll have the ability to install all dependencies of a bundle without having to list them all in .zshrc.

You can modify `antigen bundle name-of-bundle` so that antigen looks for `name-of-bundle` in `node_modules` (you can have ied install to zsh_bundles instead the default node_modules or something), then loads the bundle. Bundles can use the `antigen` API as a sort of import/require mechanism (like JavaScript's `require` and now `import`), so a bundle could do

```zsh
antigen bundle some-bundle

# ... rest of bundle code
```

or, changing the name:

```zsh
antigen import some-bundle

# ... rest of bundle code
```

You could even just define the import command

```zsh
import some-bundle

# ... rest of bundle code
```

but that would have more chance of conflicting with something (but probably won't).

That would load `some-bundle` and all of it's dependencies before running the `... rest of bundle code`. `antigen bundle/import` (if it doesn't already) would know whether that bundle was already loaded or not, and wouldn't load it again if it was.

You could even define an export command.

```zsh
antigen import some-bundle

# ... rest of bundle code

antigen export  ...
```

**Comment by trusktr** [comment]
You could even take things further by running all module code inside a zsh function, making it's own scope, then you'd reduce plugins from (sometimes randomly) conflicting. 

I think this would be awesome.

**Comment by trusktr** [comment]
The current packages in the community can be treated specially, like bundles with no dependencies, so they can just work. Perhaps if a "package.json" (or renamed if you want) isn't found, then the bundle is assumed to be an old-style bundle. It get's loaded into `node_modules` (or `zsh_modules`), then gets sourced just like bundles currently do.

**Comment by desyncr** [comment]
It's a cool idea but I think most plugins/scripts are self-contained (requiring no deps) and don't follow semver. I think being able to require branches is _enough_ for antigen's scope.

**Comment by b4b4r07** [comment]
Hi, [zplug](https://github.com/b4b4r07/zplug) (zsh plugin manager) can manage dependencies between plugins.

**Comment by trusktr** [comment]
@b4b4r07 Nice! Does it support a way for plugins to specify dependencies without the end user having to specify the relationship? What does `on:` do, there's not much on that.

**Comment by desyncr** [comment]
Please continue this discussion on the appropriate channels. I'm closing this as there is a separated solution.
