### ISSUE TITLE
[feature request] antigen search

### ISSUE THREAD

**Issue by Fandekasp** [zsh-users/antigen#160]
Are there any plans for a search feature? I would find it very useful.

For example, I've just installed [peco](https://github.com/peco/peco), and I'm not finding a zsh plugin for it on google, which seems weird. Verifying with a `antigen search peco` would be great.

**Comment by Fandekasp** [comment]
just found a snippet for peco
```
# s[Enter] で 任意ホストにssh接続
function s() {
  ssh $(awk '
    tolower($1)=="host" {
      for (i=2; i<=NF; i++) {
        if ($i !~ "[*?]") {
          print $i
        }
      }
    }
  ' ~/.ssh/config | sort | peco)
}
```
Anyways, my question still holds :)

**Comment by desyncr** [comment]
Hi @Fandekasp Thanks for the suggestion.

I think a search functionality would turn out quite useful, despite it may go a bit beyond Antigen's functionality IMO.

There are a few issues with the implementation though: The development and maintenance of a web site (with an API), the search functionality would need a more or less complex parser to display search and so on so forth.

So, while useful it's quite a huge project for now. Unless somebody would like to take this project in their hands, I'll close this for now.
