### ISSUE TITLE
Git autocompletion only enabled when manually invoke `antigen apply`

### ISSUE THREAD

**Issue by hulufei** [zsh-users/antigen#161]
Hi, I just encounter this weird issue, here is my `.zshrc`:

```
[ -e "${HOME}/.zshrc_local" ] && source "${HOME}/.zshrc_local"

source $HOME/.nvm/nvm.sh
source $HOME/.antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle common-aliases
antigen bundle git
antigen bundle npm
antigen bundle akoenig/npm-run.plugin.zsh
# aliases: h for history, hsi for grepping history
antigen bundle history
# Run `vundle` `vundle-clean` immediately etc
antigen bundle vundle
antigen bundle tmux
antigen bundle tmuxinator
antigen bundle fasd
antigen bundle nojhan/liquidprompt
antigen bundle tarruda/zsh-autosuggestions

# Enable autosuggestions automatically.
zle-line-init() {
  zle autosuggest-start
}
zle -N zle-line-init

antigen apply
```

I started a new terminal, tried to use `<TAB>` to auto complete git command, but didn't work. If I manually run `antigen apply`, auto completion just worked.

Please help, thx

**Comment by justbuchanan** [comment]
It looks like this is by design.  From the readme:

> It is possible to load completions as and when a bundle is specified with the bundle command, in which case this command would not be necessary. But loading the completions is a time-consuming process, so if the completions were loaded at every call to antigen bundle, your shell will start noticeably slow when you have a good number of bundle specifications.

**Comment by hulufei** [comment]
@justbuchanan thanks, but the last line in my `.zshrc` is `antigen apply`, I think it will do the work.

And if this is by design, let me ask another question: How to apply auto completion on shell start?

**Comment by justbuchanan** [comment]
My mistake, I didn't see the `antigen apply` at the end.  I tried out your config and it seemed to work fine for me.  I did get this warning:

~~~{.sh}
⏚ [justin:~] 1 % zsh-autosuggestions: The autosuggest-start widget is deprecated. For more info, see the README at https://github.com/zsh-users/zsh-autosuggestions.
~~~

but git completion worked fine for me.

**Comment by desyncr** [comment]
@hulufei Same behavior as @justbuchanan reported.

**Comment by yifeikong** [comment]
I have the same problem, but by putting `antigen apply` to the very end of zshrc seems to work for me. Maybe there are some other configs in my zshrc that overrides antigen apply. I will report if I find out the cause
