### ISSUE TITLE
Some prompt themes missing components

### ISSUE THREAD

**Issue by Poohblah** [zsh-users/antigen#165]
![screenshot from 2016-07-02 02-05-47](https://cloud.githubusercontent.com/assets/3742215/16539214/8a7f0016-3ff9-11e6-9502-2eb6a18a77ca.png)

Some themes, such as the `robbyrussell` and `simple` themes, seem to be missing components, while others, such as `bira` and `funky`, seem to have all components, as demonstrated in the above screenshot.

I use `grml-zsh-config` and I'm trying antigen for the first time. I'm on Arch Linux and I've installed `gmrl-zsh-config-git` and `antigen-git` via the AUR.  Here is my `~/.zshrc`:

```
# vi keybindings
set -o vi
bindkey "^?" backward-delete-char
bindkey "^H" backward-delete-char

# "prompt off" disables gmrl's prompt theme
# this is necessary to let antigen themes work properly
prompt off
source /usr/share/zsh/scripts/antigen/antigen.zsh
autoload -Uz colors && colors
setopt promptsubst
antigen use oh-my-zsh
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle git
antigen theme bira
```

**Comment by HeroCC** [comment]
It has something to do with local variables in themes, antigen doesn't like them. See #122

**Comment by Poohblah** [comment]
Ok, I'll close this as a dupe of #122.
