### ISSUE TITLE
Latest release breaks plugins/themes

### ISSUE THREAD

**Issue by xasx** [zsh-users/antigen#219]
Hi, after auto-updating antigen this morning, I experience troubles with

* zsh-navigation-tools (as plugin of oh-my-zsh)  
  Invoking Ctrl-R gives me the error:  
```
_zsh_highlight_call_widget:2: znt-history-widget: function definition file not found
```
* bhilburn/powerlevel9k theme  
  cd-ing into a Git directory gives me:  
```
set_default:typeset:4: not valid in this context: POWERLEVEL9K_/HOME/ALLCAPSUSERNAME/.ANTIGEN/REPOS/HTTPS-COLON--SLASH--SLASH-GITHUB.COM-SLASH-BHILBURN-SLASH-POWERLEVEL9K.GIT/POWERLEVEL9K.ZSH-THEME_UNTRACKED_VISUAL_IDENTIFIER_COLOR
```

I already filed this misleadingly to robbyrussell/oh-my-zsh#5403.

I came to work around this by time-warping antigen into the past:

```
git checkout 246aeb80 
```
which made both issues disappear. This is the release of 1.1.0 afaics.
I.o.w. 1a1d3ce4cda15c55835113326f338551299bc25d is the culprit.

My bisect skills are not ... existing at all to date, so I cannot dig deeper into it.

Any idea how to fix it?

**Comment by desyncr** [comment]
For the time being:

For zsh-navigation-tools: 
fpath+=("$ANTIGEN/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git/plugins/zsh-navigation-tools")

For some reason it's not being added to fpath.

**Comment by desyncr** [comment]
For powerlevel9k. I'm using latest from master and it works OK.

Using some powerlevel9k custom config? Branch?

**Comment by desyncr** [comment]
Please re-open when you have more info about powerlevel9k issue. I'm keeping an eye on it though. @xasx
Thanks for reporting.

**Comment by xasx** [comment]
Strangely this does not work for me.

* ZNT gives me the same error after checking out tag v1.1.1, 
  or even adding the repo to the fpath manually (do I need to call anything after issuing this in a terminal?)
* I have some variables set for powerlevel9k

This is my `.zshrc`:
```
source /opt/antigen/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle zsh-navigation-tools
antigen bundle docker
# antigen bundle docker-compose
antigen bundle mvn
antigen bundle command-not-found

antigen bundle StackExchange/blackbox

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# Additional completions
antigen bundle zsh-users/zsh-completions src

# Auto-Updater
antigen bundle unixorn/autoupdate-antigen.zshplugin

# does not work, dunno y
# antigen bundle zsh-users/zsh-autosuggestions

POWERLEVEL9K_MODE='awesome-fontconfig'
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M:%S %d.%m.%y}"
POWERLEVEL9K_OK_ICON=$'\UF00C'
POWERLEVEL9K_FAIL_ICON=$'\UF00D'
POWERLEVEL9K_VCS_GIT_ICON=$'\UF296'
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX="\UF120 "
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status time)

antigen theme bhilburn/powerlevel9k powerlevel9k

antigen apply

export PATH=$HOME/bin:/usr/local/bin:/usr/local/git/bin:/usr/local/hg/bin:$HOME/lib/gsc/bin:$PATH
export MANPATH="/usr/local/man:/usr/local/git/share/man:/usr/local/hg/share/man:$MANPATH"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/xasx/.sdkman"
[[ -s "/home/xasx/.sdkman/bin/sdkman-init.sh" ]] && source "/home/xasx/.sdkman/bin/sdkman-init.sh"
```

Unfortunately, this has serious impact to my productivity, I heavily work with Git repos:

![bildschirmfoto von 2016-09-13 08-48-16](https://cloud.githubusercontent.com/assets/1582730/18464069/ea4c2fcc-798e-11e6-8a7a-0f2c2e5945ec.png)

**Comment by xasx** [comment]
@desyncr I cannot re-open this issue. You are the master :place_of_worship:

**Comment by xasx** [comment]
Follow-up on the theme issue: It is not present on all repos. Probably only those having saved stashes.

**Comment by xasx** [comment]
Follow-up on the ZNT issue: seems to be fixed. Maybe some opening&closing terminals helped there.

Follow-up on the theme issue: if I do **not set any** configuration variable for it, it works. However it is not the way I want it to be then.

**Comment by xasx** [comment]
Culprit line

**Comment by desyncr** [comment]
I'll take a closer look today. Glad ZNT issue is fixed.

**Comment by desyncr** [comment]
I can reproduce the issue with powerlevel9k. I'll take a look.

**Comment by xasx** [comment]
Thanks @desyncr - it now really seems to be fixed :gift:
