### ISSUE TITLE
Bundles not loaded in 1.1.0

### ISSUE THREAD

**Issue by ilkka** [zsh-users/antigen#230]
After I updated Antigen to 1.1.0, no bundles that I loaded in `.zshrc` were actually being loaded. I have this config there:

```
if [[ -f ~/.antigen/antigen.zsh ]]; then
  source ~/.antigen/antigen.zsh
fi

antigen use oh-my-zsh
antigen bundle heroku
antigen bundle command-not-found
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle unixorn/autoupdate-antigen.zshplugin
antigen bundle b4b4r07/enhancd
antigen bundle unixorn/git-extra-commands
antigen bundle rimraf/k
antigen bundle mafredri/zsh-async
antigen bundle sindresorhus/pure

antigen apply
```

An `antigen list` however reports no bundles being loaded, although each of those commands seems to exit with code 0. Reverting Antigen back to 1.0.4 fixes this problem.

**Comment by desyncr** [comment]
ZSH version, OS, antigen cache-reset? zcache-payload exists?

**Comment by frgmt** [comment]
ZSH: 5.2
OS: Max OSX 10.12 Sierra

`antigen cache-reset`
worked for me. But installed a fresh antigen. So maybe caching should be tweaked a bit. Or README.

**Comment by desyncr** [comment]
@frgmt Glad it works now. I'm gonna take a look how to better handle upgrades.

@ilkka Does it work with antigen cache-reset?

**Comment by ilkka** [comment]
No, sadly a cache reset it did not fix it for me.

**Comment by ilkka** [comment]
What happens after `antigen cache-reset` is that in the first new shell I open afterwards, `antigen list` lists my bundles, but my prompt works only partially, with the normal sindresorhus/pure prompt mixed with the default zsh prompt:
 
![2016-09-16 at 08 31](https://cloud.githubusercontent.com/assets/1549/18576186/ece44ff2-7be7-11e6-8e84-e0cf3e611e4f.png)

In the second new shell I open, the behaviour is again the same: `antigen list` shows nothing, prompt is the default zsh prompt.

**Comment by ilkka** [comment]
Removing all repos and `antigen/.cache` fixed things for me. I've still got one machine that exhibits this buggy behaviour if you want me to investigate more.

**Comment by melmi** [comment]
I had nearly the same problem. After a fresh install of `antigen` and playing with it, I updated my `zshrc`. But the next time I entered in my shell it couldn't load any specified bundle nor the selected theme. It was very annoying. I managed to fix the problem with a `cache-reset`, as it was recommended here.

**Comment by desyncr** [comment]
@ilkka Just keeping a copy of .zcache-payload would be enough. May be [gist](gist.github.com) it?

**Comment by ilkka** [comment]
There ya go: https://gist.github.com/ilkka/7b03f3f8a89fde8969cb24a502e56cd2

**Comment by desyncr** [comment]
Thank you. I'll take a look later today.

**Comment by NightMachinary** [comment]
I have this problem, and it doesn’t go away with removing “~/.antigen” or “antigen reset”. Freshly cloned from master, zsh is  5.6.2 (x86_64-pc-linux-gnu).
