### ISSUE TITLE
Move cache and log dirs to $ADOTDIR?

### ISSUE THREAD

**Issue by fladi** [zsh-users/antigen#244]
Since 1.1.0 the Debian package of antigen [suffers from permission problems](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=838493) when utilizing the cache or the log directory. Both are assumed to be in the same directory where antigen.zsh is installed. For the Debian package this would be `/usr/share/zsh-antigen/antigen.zsh`. Of course, `/usr/share/zsh-antigen/` is not writable for normal users.

Would it make sense to move the cache and logging to the `$ADOTDIR`, which should be safe to assume that it can be written to by the user running antigen?

**Comment by desyncr** [comment]
Sure thing. Will be available in next bugfix release v1.1.4.

**Comment by fladi** [comment]
Thanks!
