### ISSUE TITLE
Fix tests on Mac OS (Yosemite) with Git >= 2.x

### ISSUE THREAD

**Issue by desyncr** [zsh-users/antigen#263]
A few tests throw errors due to git output is different from the expected one.
Git version 2.8.4. Issue probably present in all 2.x versions.

**Comment by Hoverbear** [comment]
Would this be the cause of this error?

```
git add<tab>
_call_function:22: _git-add: function definition file not found
```

**Comment by desyncr** [comment]
@Hoverbear There are errors due to git output format changes between versions and sed/grep flags IIRC.
Your issue may be due to antigen not loading oh-my-zsh correctly. You may raise an issue for it.

**Comment by Hoverbear** [comment]
Okay, perfect. Thanks. I'll explore a bit more and raise an issue if I don't figure it out. Sorry to pollute this one. :)

**Comment by desyncr** [comment]
No problem. Thanks for taking a look at it 👍

**Comment by desyncr** [comment]
Fixed with https://github.com/zsh-users/antigen/pull/365.
