### ISSUE TITLE
_git-add: Function definition file not found.

### ISSUE THREAD

**Issue by Hoverbear** [zsh-users/antigen#268]
Using:

* OS X 10.12
* zsh 5.2 (x86_64-apple-darwin16.0)
* git version 2.8.4 (Apple Git-73)
* Antigen revision f51446564c46ec07c5ebdd12fdf7cf6a0f573ca3

![screen shot 2016-10-04 at 11 59 34](https://cloud.githubusercontent.com/assets/130903/19070122/0a31ea6a-8a2a-11e6-8e52-71a293354fa3.png)

It was suggested [here](https://github.com/zsh-users/antigen/issues/263#issuecomment-250761664) that I post it.

**Comment by desyncr** [comment]
Gotcha. Gonna take a look at it.

**Comment by Hoverbear** [comment]
Thanks! Let me know if I can provide any additional information!

**Comment by desyncr** [comment]
@Hoverbear Tried it and it seems to work (MacOS and Fedora).

_git completion usually comes with zsh installation, so it _should_ be available given you have a proper $fpath.

Try to regenerate the compdump file:

    mv .zcompdump .zcompdump.1

...and restart your shell. A new .zcompdump file should be created and hopefully your issue should be gone.

**Comment by Hoverbear** [comment]
@desyncr Hey! Thanks, it seems to have worked! Sorry to bother you with this.

**Comment by desyncr** [comment]
No problem. Happy to know it worked. It seems .zcompdump should be reset automatically on antigen reset? I'll investigate a bit more.

**Comment by FezVrasta** [comment]
I'm finding myself having to reset this file once a day at least, I just installed macOS from scratch and followed the zsh + prezto installation instructions accurately. Is there any way to debug this problem?
