### ISSUE TITLE
Custom function crashes antigen

### ISSUE THREAD

**Issue by trigun0x2** [zsh-users/antigen#270]
Function:
```
# No arguments: `git status`
# With arguments: acts like `git`
g() {
  if [[ $# > 0 ]]; then
    git $@
  else
    git status
  fi
}

# Complete g like git
compdef g=git
```
Antigen file:

```
source ~/antigen.zsh
antigen bundle git
antigen apply
```

Tested in tmux 2.2 running antigen and zsh 5.2 on two separate computers.

Crashes as soon as I type `g` in zsh.

Edit: Turns out I had git plug in, so that's causing an error?

**Comment by dmdque** [comment]
You've got to unalias g

**Comment by dmdque** [comment]
When using this config:

    alias g='git'
    g() {
      if [[ $# > 0 ]]; then
        git $@
      else
        git status
      fi
    }

I get:

    $ zsh
    $ g
    [1]    99759 segmentation fault  zsh

Which is the source of the problem. From `man bash`:
> Aliases are expanded when a function definition is read,  not  when  the  function is executed, because a function definition is itself a command.

It seems that it's caused by never-ending recursion. But I find it weird that it segfaults instead of behaving like:

    $ pwd() { pwd }
    $ pwd
    $ pwd: maximum nested function level reached

**Comment by desyncr** [comment]
@trigun0x2  As @dmdque very well described it, the issue is the interaction between your `g` function and `git` plugin, which does [defines](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/git/git.plugin.zsh#L41) a `g` alias.

@dmdque That's a good question for the zsh-dev guys.
