### ISSUE TITLE
Problems with keys in macOS

### ISSUE THREAD

**Issue by jordi9** [zsh-users/antigen#285]
Hi,

Since v1.1.4 I have problems with regular keys, like HOME or cycling through command history with up & down arrow. eg: 

* HOME key does nothing
* When I type `ssh` + key up, I expect to cycle through ssh commands, but instead I goes to previous entered command.

Using v1.1.3 works fine. In v1.2.0 I found the same problems. I'm using macOS Sierra 10.12. I looked for issues with iTerm2 and the like, but I believe everything is in the right place.

Let me know how can I help or if you need more information.

**Comment by desyncr** [comment]
@jordi9 Hello there. Please provide a minimum .zshrc/.antigenrc configuration file in order to see what configuration and bundles you're using. Zsh version?

**Comment by jordi9** [comment]
Hi @desyncr,

Here's my .zshrc, it's pretty straightforward 

```
source ~/.homesick/repos/dotfiles/antigen/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle git-extras
antigen bundle heroku
antigen bundle lein
antigen bundle command-not-found
antigen bundle mvn

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search

# Load the theme.
antigen theme $HOME/.homesick/repos/dotfiles themes/in-fino-veritas --no-local-clone

# Tell antigen that you're done.
antigen apply
```

I guess it's not related to `oh-my-zsh`, because keys are working with v1.1.3

I'm using `zsh 5.2 (x86_64-apple-darwin15.6.0)`

hth

**Comment by kmikolaj** [comment]
I have the same problem with Ubuntu 16.04 and Gnome Terminal. I can't cycle through history with Up arrow key. Keys like Home, End won't work. Config is similar to @jordi9.

Checkout on v1.1.3 solved the problem. 

It is possibly that somehow oh-my-zsh lib content is not sourced?
Because sourcing "$OHMYZSHDIR/lib/key-bindings.zsh" makes Home and End keys working again.

**Comment by desyncr** [comment]
@jordi9 @kmikolaj Thanks for the info. I'm gonna take a look today.

In [1.1.4](https://github.com/zsh-users/antigen/releases/tag/v1.1.4) were huge changes regarding bundle loading, so this could have been affected by that.

Thank you both for reporting.
