### ISSUE TITLE
gem and pip completion not working

### ISSUE THREAD

**Issue by silvadev** [zsh-users/antigen#294]
The command completion for `pip` and `gem` not working using `antigen bundle` from on-my-zsh.
Same plugins works if loaded with oh-my-zsh directives in `.zshrc`.
`plugins=(gem pip etc)`

Before opening this issue was only used the following lines in `.zshrc`:
```zsh
source antigen.zsh
antigen use oh-my-zsh
antigen bundle gem
```
But problem still.

**Comment by desyncr** [comment]
Using lastest antigen (`1.2.1`) and doing both:

    antigen bundle gem
    antigen apply

and editing `.zshrc` with

    antigen use oh-my-zsh
    antigen bundle gem
    antigen apply

Seems to work as expected (tried with both `pip` and `gem`).

Did you tried to clean your cache with `antigen reset`? (alternatively `antigen apply` to see completion changes on the current shell).

**Comment by silvadev** [comment]
Yeah! The `antigen reset` command works for me, thanks!

**Comment by desyncr** [comment]
@silvadev Glad it worked!
