### ISSUE TITLE
No longer uses history-beginning-search-backward on zsh 5.1.1

### ISSUE THREAD

**Issue by MichaelRupertDev** [zsh-users/antigen#295]
When using the up arrow on zsh version 5.1.1 with the following zshrc 

```
source ~/antigen/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle heroku
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# Load the theme.
antigen theme agnoster

# Tell antigen that you're done.
antigen apply
```

the history works as it does in default bash, going through items reverse chronologically, rather than the last usage of that command.

Can be seen here: https://asciinema.org/a/39avoj0jxs256otgoutmd6f0w

**Comment by desyncr** [comment]
@MichaelRupertDev Using Antigen `v1.2.x` worked as expected on Ubuntu `16.04.1`. Did you tried `antigen reset`?
