### ISSUE TITLE
Sign git commits & releases (tags)

### ISSUE THREAD

**Issue by rugk** [zsh-users/antigen#301]
You should consider signing git commits & releases.

* [onionshare#221 (comment)](https://is.gd/7vU4oK)
* It is also displayed on GitHub: https://github.com/blog/2144-gpg-signature-verification
* Here is GitHub's help for this: https://help.github.com/articles/generating-a-gpg-key/
* And here is how you can properly sign releases: https://wiki.debian.org/Creating%20signed%20GitHub%20releases

**Comment by desyncr** [comment]
I was considering signed releases but ended up considering it lower priority due to lack of time.

I'll take a second look and see if 2.x can be a signed release.

**Comment by desyncr** [comment]
We should be signing commits/PR and tags from now on.
