### ISSUE TITLE
Can't install latest version (1.2.0)

### ISSUE THREAD

**Issue by DestyNova** [zsh-users/antigen#305]
The webpage provides these instructions:

> Install Antigen from our main repository for the latests and greatests version available:
> ```
> curl https://cdn.rawgit.com/zsh-users/antigen/v1.2.0/bin/antigen.zsh > antigen.zsh
> ```

However, there are no instructions for what to do with this file. I tried executing it with `zsh antigen.zsh`, which produces no output, and the `~/.antigen` directory is not created. What am I missing here?

**Comment by DestyNova** [comment]
Ok, so I was able to move past that by using `git clone` to put everything into `~/.antigen/antigen`, and now I'm facing this:
```
% Installing robbyrussell/oh-my-zsh... Done. Took 3s.
sed: -e expression #1, char 0: unmatched `{'
sed: -e expression #1, char 0: unmatched `{'
sed: -e expression #1, char 0: unmatched `{'
sed: -e expression #1, char 0: unmatched `{'
sed: -e expression #1, char 0: unmatched `{'
sed: -e expression #1, char 0: unmatched `{'
sed: -e expression #1, char 0: unmatched `{'
sed: -e expression #1, char 0: unmatched `{'
sed: -e expression #1, char 0: unmatched `{'
sed: -e expression #1, char 0: unmatched `{'
sed: -e expression #1, char 0: unmatched `{'
sed: -e expression #1, char 0: unmatched `{'
sed: -e expression #1, char 0: unmatched `{'
sed: -e expression #1, char 0: unmatched `{'
sed: -e expression #1, char 0: unmatched `{'
sed: -e expression #1, char 0: unmatched `{'
sed: -e expression #1, char 0: unmatched `{'
sed: -e expression #1, char 0: unmatched `{'
sed: -e expression #1, char 0: unmatched `{'
Installing zsh-users/zsh-syntax-highlighting... Done. Took 2s.
sed: -e expression #1, char 0: unmatched `{'
```
Maybe another issue already exists for that problem; I'll check.

**Comment by DestyNova** [comment]
A `git bisect` run identifies the following commit as the start of the weird `sed` errors:
```
356f750ba4705c4a100f14e4f558ed5ac3ee7db4 is the first bad commit
commit 356f750ba4705c4a100f14e4f558ed5ac3ee7db4
Author: DC* <syncr@riseup.net>
Date:   Fri Oct 14 22:52:28 2016 +0200

    Fix local variable in themes/bundles (#284)
    
    * Fix local variable in themes/bundles
    * Update cache tests for fix on local variables
    * Only pre process "local" for themes

:040000 040000 efb405a68a108c9737baee08ce2dac4533e3845e 6951665fc68be63137e6f897f970a7b7bd32fa8c M   bin
:040000 040000 0c82e98d19f55ac3ce341304b0b7e0dfbfd838c4 b34ecfa561764726239a5478960e297afa7d96d8 M   src
:040000 040000 93c2a28757595e2b785b784780b09f7025bfa430 aed1047945f8c994e9baf94930d97064d308d7ce M   tests
```

**Comment by desyncr** [comment]
Please provide zsh version, OS version.
Thanks.

**Comment by DestyNova** [comment]
Sure:
zsh: `zsh 5.1.1 (x86_64-ubuntu-linux-gnu)`
OS: `Ubuntu 16.04.1 LTS`

**Comment by desyncr** [comment]
@DestyNova  I'm not sure how did you installed antigen but these are the most succinct install steps:

1- Download antigen to your `$HOME` path.

    curl https://cdn.rawgit.com/zsh-users/antigen/v1.2.1/bin/antigen.zsh > $HOME/antigen.zsh

2- Edit `$HOME/.zshrc` to load `$HOME/antigen.zsh`:

    source $HOME/antigen.zsh

3- Edit `$HOME/.zshrc` to configure some bundles:

    antigen use oh-my-zsh

    antigen bundle git
    antigen bundle zsh-users/zsh-syntax-highlighting

    antigen theme muse

    antigen apply


[Here's](https://gist.github.com/desyncr/86e50a15d02b8fbbf9a1593a877b3da0) the final `.zshrc` as an example.

**Comment by desyncr** [comment]
I can't seem to reproduce [this](https://github.com/zsh-users/antigen/issues/305#issuecomment-258654553). If there is further information please comment.

I'm closing this for now.
