### ISSUE TITLE
Antigen interferes with completion in weird ways

### ISSUE THREAD

**Issue by qstrahl** [zsh-users/antigen#312]
```
bindkey "${terminfo[kcbt]}" reverse-menu-completion
```

The above should make shift-tab go backward after you start tabbing through completion options. Without antigen, this works as expected. If you source `bin/antigen.zsh`, however, it doesn't work right; shift-tab will do nothing but stop completion.

From what I can gather, it's trying to restart completion instead of move backward through the current completion list. Since the completion options are put onto the command line as you tab through them, this just ends completion (because it tries to start completion with a full match on the line).

I tried commenting out some of the `compinit` related lines in `bin/antigen.zsh` and that made the issue go away, but I haven't been able to narrow it down past that.

**Comment by qstrahl** [comment]
Managed to narrow it down a bit. Problem goes away when I comment out the following:

In function `-antigen-env-setup`: ```
    # Setup antigen's own completion.
    autoload -Uz compinit
    if $_ANTIGEN_COMP_ENABLED; then
        compinit -C
        compdef _antigen antigen
    fi
```

And in function `antigen-apply`: ```
    # Load the compinit module. This will readefine the `compdef` function to
    # the one that actually initializes completions.
    autoload -U compinit
    if [[ -z $ANTIGEN_COMPDUMPFILE ]]; then
        compinit -i
    else
        compinit -i -d $ANTIGEN_COMPDUMPFILE
    fi
```

**Comment by desyncr** [comment]
I'll take a look later today.

Meanwhile could you post your `.zshrc` configuration?, Zsh version and OS?

**Comment by qstrahl** [comment]
A .zshrc capable of reproducing the issue is in the first post. One line. Zsh version is 5.2, OS is Arch Linux. But actually now that I'm poking at this more, it looks like loading `compinit` at all -- with or without antigen -- is enough to cause this screwup... :S

**Comment by desyncr** [comment]
You should probably try `rm -f ~/.zcompdump*`. Tried with latest `antigen` on `zsh 5.2`, worked as expected.

**Comment by desyncr** [comment]
Closing this up for now. Comment if you see it's still behaving in this way and it's effectively related to `antigen`.

Thanks for reporting.
