### ISSUE TITLE
antigen not populating fpath correctly

### ISSUE THREAD

**Issue by yacoob** [zsh-users/antigen#313]
For some reason, antigen isn't setting correct paths for installed bundles in fpath, resulting in zaw failing to start:
```
(anon):205: filter-select: function definition file not found
(anon):bindkey:206: no such keymap `filterselect'
```
This is not surprising, as `fpath` entry for zaw looks like this:
```
/home/yacoob/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zaw.git//
```
(note the double slash at the end)

On a different Linux host, with same version of antigen and zaw, `fpath` gets set correctly:
```
/home/yacoob/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zaw.git/functions
```

Is there any debug mode I can enable for antigen so I can see why is it making a bad decision when it comes to setting fpath?
Details: antigen 1.2.1, zsh 5.1.1, Linux (3.13.0)

**Comment by desyncr** [comment]
This happens due to how [zaw determines](https://github.com/zsh-users/zaw/blob/master/zaw.zsh#L18) the current path in order to add `functions` to `fpath`, which works without antigen's cache involved, otherwise it fails.

**Comment by yacoob** [comment]
Why is antigen able to set the path correctly on the other host then?

**Comment by desyncr** [comment]
Not sure about that. May be running with caching disabled (_ANTIGEN_CACHE_ENABLED=false).

You should check `~/.antigen/.cache/.zcache-payload`. It does contains the final `fpath` generated by antigen. If they differ then there's another problem.

**Comment by yacoob** [comment]
I've checked that: on all of my boxes where I don't see the boxes, I had old version of antigen installed (+1year old), and no caching was enabled. After updating antigen and restarting zsh, I've started seeing same problems (wrong `fpath`) with the other bundle I use (`zsh-users/zsh-syntax-highlighting`). Disabling cache helped.

Please tell me if you need any other information.

**Comment by desyncr** [comment]
I haven't seen errors with `zsh-syntax-highlighting`. What's the issue?

**Comment by yacoob** [comment]
```
zsh-syntax-highlighting: highlighters directory '/Users/yacoob/.antigen/.cache/highlighters' not found.
zsh-syntax-highlighting: failed loading highlighters, exiting.
```

**Comment by desyncr** [comment]
I'll try to reproduce it on `zsh 5.1.1` but I can't see that error with latest `zsh-users/zsh-syntax-highlighting`, antigen `v1.2.1` or above.

**Comment by desyncr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update single plugin](https://trello.com/c/mAizKuGN/45-update-single-plugin)

**Comment by beedaan** [comment]
I'm having the same problem as @yacoob.  I try to install zsh-syntax-highlighters using `antigen init` and I get the same error.  However, I can successfully install the highlighters using `antigen bundle zsh-users/zsh-syntax-highlighting` from the command line.  I think it must have something to do with the cache, but I don't know.

I'm using zsh 5.2 and antigen v1.3.2

**Comment by desyncr** [comment]
I'm gonna take a look.

**Comment by desyncr** [comment]
I does seem to work as expected using both load methods: `init` and `bundle`.  What's the error you see?

**Comment by beedaan** [comment]
I am getting the same error as @yacoob 
```
zsh-syntax-highlighting: highlighters directory '/Users/bheussler/.antigen/.cache/highlighters' not found.
zsh-syntax-highlighting: failed loading highlighters, exiting.
```

This is what my antigen.zsh looks like
```bash
source /usr/local/share/antigen/antigen.zsh
antigen init /Users/bheussler/.dotfiles/zsh/antigenrc
```

which loads my antigenrc
```
# Load the oh-my-zsh's library.
antigen use oh-my-zsh

antigen bundle brew
antigen bundle bundler
antigen bundle docker
antigen bundle extract
antigen bundle gem
antigen bundle git
antigen bundle mvn
#antigen bundle npm
antigen bundle osx
antigen bundle vagrant
antigen bundle zsh-users/zsh-syntax-highlighting

# Load the theme.
antigen theme arrow

# Tell antigen that you're done.
antigen apply
```

**Comment by desyncr** [comment]
Tried your set up and works as expected. Try: `antigen reset`, to reset cache.
Also what's the output of `antigen version`, just to check.

**Comment by beedaan** [comment]
I think I found the issue.  I'm currently running Antigen v1.3.2 installed from Homebrew.  I did major upgrade from [an earlier version](https://github.com/zsh-users/antigen/tree/1359b9966689e5afb666c2c31f5ca177006ce710) (version 1?).  The fix was to wipe out the `.antigen/` directory in my home and have antigen reinstall plugins.  Works great so far!

**Comment by desyncr** [comment]
Good to hear. I'll investigate how to avoid issues between major upgrades.
I believe we currently reset cache on selfupdate.

Best regards
