### ISSUE TITLE
Antigen 'apply' takes 5 seconds

### ISSUE THREAD

**Issue by orf** [zsh-users/antigen#324]
Hey, I've been using `antigen` for the last year or so and it's been amazing. 

However I just purchased Kaspersky Internet Security for my mac during black Friday and now running a simple `antigen apply` *with no bundles or themes* takes over 5 seconds. My normal `.zshrc` with plugins takes upwards of 20-25 seconds to load now.

I realize that this is obviously because of Kaspersky, but I wanted to know what's the best way to debug this. Does `antigen` have a verbose mode? How can I profile it to see what's taking so long?

What's weird is that a 'blank' `antigen apply` takes so long, if I'm not loading any plugins or themes then what is it doing?

**Comment by desyncr** [comment]
Hey there @orf, unfortunately Antigen has no verbose mode. What I do to debug is either activating `zprof` or simply perform a binary search/git bisect depending on the issue. Take a look [here](http://blog.xebia.com/profiling-zsh-shell-scripts/).

Regarding `antigen apply`, what it does is `compinit`. Check if performing the following lines does cause an unusual delay:

    autoload -U compinit
    compinit -i -d $HOME/.compdump

**Comment by orf** [comment]
After a bit of hacky profiling with adding `echo 'something $(date +%d.%m.%y-%H:%M:%S)'` all around `antigen.zsh` it seems the culprit is `source $_ZCACHE_PAYLOAD_PATH`. This takes over 12 seconds when kaspersky is installed.

`-zcache-unhook-antigen` also takes 4 or 5 seconds as well.

I'm going to open a support request with Kaspersky to see if they have anything to say about this, but is there any way to avoid those calls? I think I know the answer: no, because they seem to be an amalgamated form of all my plugins?

**Comment by desyncr** [comment]
I don't know how Kaspersky works but it could hook `source`/`eval`/`sed`/`$()` functions/builtins.

You can disable Antigen's cache (and those calls) with:

    export _ANTIGEN_CACHE_ENABLED=false

I'll close this for now as it's not related to Antigen. Do come back with news if you have any.

Cheers.
