### ISSUE TITLE
antigen breaks tab completion of directories following paths stored in variables

### ISSUE THREAD

**Issue by rltbennett** [zsh-users/antigen#354]
Say you have a long pathname stored in a variable, like `directory="$HOME/first/second/third"`. Normally, zsh allows tab completion of directories following this variable. For instance, `cd $directory/fo<tab>` will insert `$directory/fourth`. However, will antigen enabled, this no longer works. Hitting tab brings up no completions (and the bel rings), meaning zsh no longer inspects `$directory` for its value and acts accordingly with anitgen enabled.

Tested by enabling antigen with no plugins enabled.

**Comment by desyncr** [comment]
Quickly tested locally with zsh version `zsh 5.2 (x86_64-redhat-linux-gnu)`, and Antigen `v1.3.0`. Worked as expected.

Did you tried removing `$HOME/.zcompdump` or issuing `antigen reset`? As the [troubleshooting section](https://github.com/zsh-users/antigen/wiki/Troubleshooting) suggests?

**Comment by desyncr** [comment]
Closing this for now. I'll open it up if there anything to do with antigen.

Thanks for reporting.

**Comment by rltbennett** [comment]
Thanks. antigen reset seemed to fix it.

**Comment by desyncr** [comment]
Awesome. Thank you!
