### ISSUE TITLE
Plugin return kills antigen

### ISSUE THREAD

**Issue by lukechilds** [zsh-users/antigen#386]
I just got an issue reported (https://github.com/lukechilds/zsh-nvm/issues/19) on zsh-nvm that their entire antigen install was breaking.

It looks like it was caused by the caching in antigen, it concatenates all of the files together and zsh-nvm ends with a return statement which was stopping the rest of the cache file from being executed.

So any zsh plugin that contains a return will completely break antigen.

I've removed the return as a temporary workaround, however if it's possible to resolve this on the antigen side that would probably be better so no other plugins encounter this issue.

One possible solution would be to wrap each plugin in a function rather than just concatenating the raw files. Although I'm not quite sure if that would cause issues loading the plugins via executing a function rather than sourcing a file. Thoughts?

**Comment by desyncr** [comment]
Hey there @lukechilds, we have queued up to test performance with caching references vs cache sources. So we're probably gonna fix this before 2.0 is out.

Not sure what's the need to explicitly return 0.

**Comment by lukechilds** [comment]
If the plugin ends with something like:

```shell
[[ $SOME_ENV_VAR == "true" ]] && load_plugin
```

It'll have a failing exit code if `SOME_ENV_VAR` is false. Explicitly running `return 0` will give us a non failing exit code.

**Comment by desyncr** [comment]
Now I see, it's this [condition](https://github.com/lukechilds/zsh-nvm/blob/4ba1a04f0971ca229b863799bb38781deb3225b2/zsh-nvm.plugin.zsh#L176) which may return a non-zero result.

**Comment by lukechilds** [comment]
Yeah, my tests suit fails if the script exits with a non zero exit code so I manually `return 0` so because even though the last operation in the script failed, it should have failed so everything has worked properly.

Obviously I can easily fix this by just running `true` so we always get a good exit code. I just thought I should let you guys know because if anyone does a return for any reason in a zsh plugin and someone loads it with antigen it'll completely mangle their antigen setup.

**Comment by desyncr** [comment]
Fair point. Thanks for reporting, we'll look into it.

For anyone facing this issue with other plugin you have a workaround by disabling antigen's cache:

    export _ANTIGEN_CACHE_ENABLED=false
