### ISSUE TITLE
Can't run on Cygwin

### ISSUE THREAD

**Issue by Wirone** [zsh-users/antigen#388]
I have `.zshrc`:

```
source ~/.antigen/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle git-flow-avh
antigen bundle pip
antigen bundle grunt
antigen bundle gulp
antigen bundle httpie
antigen bundle npm
antigen bundle postgres
antigen bundle redis-cli
antigen bundle symfony2
antigen bundle composer
antigen bundle zsh-autosuggestions
antigen bundle colorize
antigen bundle zsh-completions
antigen bundle command-not-found

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# Load the theme.
antigen theme candy

# Tell antigen that you're done.
antigen apply

# ... some aliases etc.
```

When I run shell I get:
```
Installing robbyrussell/oh-my-zsh... Done. Took 105s.
Installing robbyrussell/oh-my-zsh... Error! See "/cygdrive/c/Users/MY_USER/.antigen/antigen.log".
Installing robbyrussell/oh-my-zsh... Error! See "/cygdrive/c/Users/MY_USER/.antigen/antigen.log".
Installing robbyrussell/oh-my-zsh... Error! See "/cygdrive/c/Users/MY_USER/.antigen/antigen.log".
Installing robbyrussell/oh-my-zsh... Error! See "/cygdrive/c/Users/MY_USER/.antigen/antigen.log".
Installing robbyrussell/oh-my-zsh... Error! See "/cygdrive/c/Users/MY_USER/.antigen/antigen.log".
Installing robbyrussell/oh-my-zsh... Error! See "/cygdrive/c/Users/MY_USER/.antigen/antigen.log".
Installing robbyrussell/oh-my-zsh... Error! See "/cygdrive/c/Users/MY_USER/.antigen/antigen.log".
Installing robbyrussell/oh-my-zsh... Error! See "/cygdrive/c/Users/MY_USER/.antigen/antigen.log".
Installing robbyrussell/oh-my-zsh... Error! See "/cygdrive/c/Users/MY_USER/.antigen/antigen.log".
Installing robbyrussell/oh-my-zsh... Error! See "/cygdrive/c/Users/MY_USER/.antigen/antigen.log".
Installing robbyrussell/oh-my-zsh... Error! See "/cygdrive/c/Users/MY_USER/.antigen/antigen.log".
Installing robbyrussell/oh-my-zsh... Error! See "/cygdrive/c/Users/MY_USER/.antigen/antigen.log".
Installing robbyrussell/oh-my-zsh... Error! See "/cygdrive/c/Users/MY_USER/.antigen/antigen.log".
Installing robbyrussell/oh-my-zsh... Error! See "/cygdrive/c/Users/MY_USER/.antigen/antigen.log".
Installing robbyrussell/oh-my-zsh... Error! See "/cygdrive/c/Users/MY_USER/.antigen/antigen.log".
Installing zsh-users/zsh-syntax-highlighting... Done. Took 9s.
Installing robbyrussell/oh-my-zsh... Error! See "/cygdrive/c/Users/MY_USER/.antigen/antigen.log".
```
After that I have clear console without any prompt, but "working" (typing `pwd` displays my startup dir).

I check the log file and this is what I got:

```
Cloning into '/cygdrive/c/Users/MY_USER/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-syntax-highlighting.git'...
fatal: destination path '/cygdrive/c/Users/MY_USER/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git' already exists and is not an empty directory.
```

**BUT antigen does not create valid directories**, because instead creating `C:\Users\MY_USER\.antigen\repos` it creates `C:\cygdrive\c\Users\MY_USER\.antigen\repos` and clones repos there...

I've tried to load `cygwin` bundle before using `oh-my-zsh` in `zshrc`, but without effect.
```
# OS specific plugins
if [[ $CURRENT_OS == 'Cygwin' ]]; then
    antigen bundle cygwin
fi
```

It looks like `cygpath` isn't used somewhere and repos path is not converted into real Windows path.

**Comment by Wirone** [comment]
Additionally:
- I don't have cygwin installed under standard path, but on `D:\Bin\cygwin` (added to PATH variable)
- I run ZSH under ConEmu with task `D:\Bin\cygwin\Cygwin.bat -new_console:d:D:\`

`Cygwin.bat` content:
```
@echo off

D:
chdir D:\Bin\cygwin\bin
zsh -i -l
```

**Comment by Wirone** [comment]
I have figured it out. It's because I don't use Cygwin's Git, but Git for Windows. It's in my `PATH` variable and Antigen can use it, but it requires windows-style paths, not cygpaths. It's very similar problem to composer/composer#3184 but instead of checking against `php` Antigen should check if `git` is under `/bin` directory or has `/cygdrive` in path (and convert repo location with `$(cygpath -m \$dir)` if required).

I've been able to fix this locally by changing `-antigen-ensure-repo()` and `-antigen-env-setup()` (hardcoded `cygpath` usage for cloning location and `ADOTDIR` directories).

Checking for Cygwin can be done with `command -v 'cygpath' >/dev/null 2>&1` or `"Cygwin" == $(uname -o)`.

**Comment by desyncr** [comment]
Great you found out the issue :+1: .

I don't want to add explicit checks for `cygpath`, so I'm gonna explore other options.

**Comment by Wirone** [comment]
Sure, I am curious if it's possible without it. In my opinion: not ;-) Looking forward for the fix.

**Comment by rfgamaral** [comment]
@Wirone I'm also using Zsh/Antigen on Cygwin and I'm just curious if you have a reason for using Git for Windows instead of relying on Cygwin's Git.

**Comment by Wirone** [comment]
@rfgamaral To be honest, I don't remember. I think it's because I wanted to have most recent version and in Cygwin it's not always the newest one (for now it's 2.8.3 and I have 2.9.0). I probably had some issues too, but as I said - I don't remember now :-)

**Comment by Wirone** [comment]
I think it's time to close this issue since I don't use Cygwin and Windows anymore 😉 Probably not a single person is waiting for this 😅

**Comment by Nantris** [comment]
> Probably not a single person is waiting for this 😅

Ahem! Just because I have to use Windows, doesn't mean I want to go without nice stuff.

**Comment by Wirone** [comment]
@Slapbox please file new issue then, because I don't want to keep it on my issues list for another 5 years 😉

**Comment by Nantris** [comment]
@Wirone thanks for your reply! I think the best thing to do would be to re-open this and then you could unsubscribe to stop getting notifications - that would help to keep the discussion in one place. What do you think?

![image](https://user-images.githubusercontent.com/6835891/202867956-d2bffb78-9deb-4a63-b3cc-41bcef9e0509.png)

**Comment by Wirone** [comment]
@Slapbox I know I can unsubscribe, but I was talking about "[my issues](https://github.com/issues)" list - it will be there and I don't want it since I'm not interested in this issue anymore. Also it seems like @desyncr forgot about it.

You can create new issue with reference to this one and/or point to [this comment](#issuecomment-272620856) 🙂
