### ISSUE TITLE
Installation Confusion

### ISSUE THREAD

**Issue by einSelbst** [zsh-users/antigen#392]
Sorry, it's probably my fault but I'm not sure which way I have to install antigen correctly.
I just want to use it (not develop).

In the Readme under "Usage" it says I should clone the repo and add some stuff to .zshrc.
Later in the Readme under "Installation" it says I can just `brew install antigen`

Is one an alternative to the other? Are both different things?
Thanks Silvio

**Comment by desyncr** [comment]
Hey there @einSelbst these installation methods are not interchangeable. The recommended way for end-users (like yourself) is to:

- use brew, if available: `brew install antigen`
- use your  os package manager. see install instructions
- if none is available use `git`

For `brew` I believe you have to add `source $HOMEBREW_PREFIX/share/antigen/antigen.zsh` to your `~/.zshrc`.

**Comment by einSelbst** [comment]
Thanks for your quick and helpful answer @desyncr !

Because of the linear reading of the Readme it might be helpful to have a reference to the "Installation" section from the top of the "Usage" section, something along the lines of 

> [...]  Sweet. Let's do it.
> There are several installation methods available in the "Installation" section or you can use `git`:
>
> First, clone this repo, [...]

If you like I can send a PR.

After install via brew it told me:
 "Your copy of antigen doesn't appear to be a git clone.  The 'selfupdate' command cannot work in this case."   which is according to the explanation given in the Readme under "selfupdate". 
Am I right to assume that brew will handle the updating for me? (Sorry for the noobish questions, I just want to make sure antigen works nicely)

**Comment by desyncr** [comment]
Yes, when using brew, updates are handled through brew itself. It is often updated so no worries about it.

If you're up for a PR please go ahead. More and better documentation is always welcome!
