### ISSUE TITLE
Bug in zsh 4.3.11

### ISSUE THREAD

**Issue by TBird2001** [zsh-users/antigen#394]
I'm using antigen on a Red Hat Linux 6 server, which runs zsh 4.3.11.  When I did a pull recently, I got following errors when antigen tried to load:
`(eval):29: parse error near '}'`
`(eval):20: parse error near '}'`
`-zcache-antigen-hook:21: command not found: -zcache-antigen-theme`

I traced the first instance of an error to commit a834db04. The error there is simply:
`(eval):25: parse error near '}'`

Being a novice zsh user, I can't help troubleshoot more than that without some help; but I can help with troubleshooting if needed.

**Comment by desyncr** [comment]
I'm gonna take a look today. `4.3.11` is a supported version so it should work.

**Comment by desyncr** [comment]
Maybe related to https://www.zsh.org/mla/users/2011/msg00823.html, https://www.zsh.org/mla/users/2011/msg00034.html

**Comment by desyncr** [comment]
Our test suite is passing and a bit of manual test also gave good result, but if you could give it a quick look it'll be great feedback. Fix is in https://github.com/zsh-users/antigen/pull/395. @TBird2001

**Comment by TBird2001** [comment]
That appears to have fixed the problem. Thanks for the quick response. @desyncr

**Comment by desyncr** [comment]
@TBird2001 Awesome! Merged into `develop`, should be available in `1.3.5` due to be releases today.
