### ISSUE TITLE
Script fails if the `which` command is not working Cent OS 7

### ISSUE THREAD

**Issue by lovepreetkaul** [zsh-users/antigen#405]
Hi, 
I am using Cent OS 7 64 bit. While running my antigen install, the script fails after echoing `Antigen: Please install git to use Antigen.`  even when `git` is installed. After further investigation, it is the `/usr/bin/which` command that is broken and `/usr/bin/which-command` works instead. Since `which` causes problems I suggest we switch to alternate/multiple ways of checking if git is installed or not.

**Comment by desyncr** [comment]
This is solved in `v2.0.0` by using `$+commands[git]` rather than `git`. `v2.0.0` is scheduled for March 4th.

Thanks for reporting.

**Comment by desyncr** [comment]
Furthermore, I tried Cent OS 7 and it seems it works correctly.

```bash
[antigen@dploy]~% antigen list
You don't have any bundles.
[antigen@dploy]~% which git
/usr/bin/git
[antigen@dploy]~% uname -a
Linux dploy 3.10.0-514.6.1.el7.x86_64 #1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[antigen@dploy]~% cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
[antigen@dploy]~%

```

**Comment by desyncr** [comment]
Closing this for now. Thanks for reporting.
