### ISSUE TITLE
"_history-substring-search-end:13: _zsh_highlight: function definition file not found"

### ISSUE THREAD

**Issue by qaisern** [zsh-users/antigen#406]
I think i have manged to mess my zsh shell .. I am getting the following message whenI use the up or down arrow keys

"_history-substring-search-end:13: _zsh_highlight: function definition file not found"

Just to give you a background ...

I installed antigen using curl https://cdn.rawgit.com/zsh-users/antigen/v1.4.0/bin/antigen.zsh > antigen.zsh source antigen.zs

This worked fine ..

Someone mentioned to install it via brew .. so I installed it via brew ... This is when antigen stopped working and the highlighter ...

I tried installing antigen again via :- curl https://cdn.rawgit.com/zsh-users/antigen/v1.4.0/bin/antigen.zsh > antigen.zsh source antigen.zs

antigen works while i am in the shell ...but the highligher is not working ...

But when I re-launch a new shell and type the antigen command I receive the following message "zsh: command not found: anitgen"

and also the following message when i use the up and down arrow keys "_history-substring-search-end:13: _zsh_highlight: function definition file not found"

Your help would be kindly appreciated

**Comment by desyncr** [comment]
Can you provide your `.zshrc` configuration? It will be really helpful to see how you've configured:

- sourcing antigen
- bundles used
- cache and possible other env variables1
- zsh opts

It seems you're not properly loading `antigen.zsh`.

**Comment by desyncr** [comment]
Closing this for now. Comment if you have any more information.
