### ISSUE TITLE
Bundles fail to work after antigen update

### ISSUE THREAD

**Issue by marmistrz** [zsh-users/antigen#412]
Hi,

I had an old version of Antigen installed on my computer. Now I got an update from AUR and installed it. Now, whenever I launch `zsh`, I get: 

    zsh: command not found: git_super_status                                                                                                            

Mysteriously, everything seems to work once I manually source `~/.zshrc`

`git_super_status` should be provided by `olivierverdier/zsh-git-prompt`
My .zshrc:
```
HISTFILE=~/.histfile
HISTSIZE=2000
SAVEHIST=2000
setopt nomatch
bindkey -e

#Completion
autoload -Uz compinit && compinit

#Needed for colorful prompts
autoload -U colors && colors
setopt promptsubst
setopt HIST_IGNORE_SPACE

#Antigen
source /usr/share/zsh/share/antigen.zsh
antigen use oh-my-zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
antigen bundle olivierverdier/zsh-git-prompt
function prompt_char {
	if [ $UID -eq 0 ]; then echo "#"; else echo $; fi
}

PROMPT=$'%{$fg_bold[blue]%}%n@%m %{$fg[green]%}%d %{$fg_bold[white]%}[%?] %{$reset_color%}$(git_super_status)\
%D{[%X]} %{$fg_bold[green]%}%_$(prompt_char)%{$reset_color%} 
```

**Comment by desyncr** [comment]
It seems you're missing `antigen-apply`:

.zshrc:

    ...
    antigen bundle olivierverdier/zsh-git-prompt
    antigen apply

**Comment by marmistrz** [comment]
Seems to work, thanks!

**Comment by desyncr** [comment]
Thank you for reporting.
