### ISSUE TITLE
Zsh theme from a custom repo not loading automatically when opening a new terminal.

### ISSUE THREAD

**Issue by lovepreetkaul** [zsh-users/antigen#416]
When I use any theme from oh_my_zsh repo, it loads fine when starting a new terminal. But when I specify a theme from different repo(as described in the documentation), It does not load when starting a new terminal. I have to manually source zshrc for the theme to load. 

Do let me know if I'm doing something wrong. Thanks

My .zshrc

```
#
# Antigen 
#

source ~/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle mercurial
antigen bundle command-not-found

# Zsh completions
antigen bundle zsh-users/zsh-completions

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# Load the theme.
#antigen theme lovepreetkaul/zsh-themes themes/senti.zsh-theme
antigen theme steeef
# Tell antigen that you're done.
antigen apply
```

**Comment by desyncr** [comment]
Your configs looks right. What Antigen version are you using?:

    antigen version
    zsh --version
    uname -a

**Comment by desyncr** [comment]
Tested with `1.4.1 and `v2` and it seems to work as expected.

**Comment by lovepreetkaul** [comment]
These are the versions I am using:

```
Antigen v1.4.0
zsh 5.1.1 (x86_64-ubuntu-linux-gnu)
Linux workstation 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by lovepreetkaul** [comment]
Hi, 
This seems strange but it is working as expected now and I am not able to reproduce the issue. Thanks for looking into it.

**Comment by desyncr** [comment]
Well, I'll keep an eye on it.
