### ISSUE TITLE
different behavior for `antigen theme robbyrussell` if executed before or after `antigen apply`

### ISSUE THREAD

**Issue by Stefanqn** [zsh-users/antigen#418]
I use oh-my-zsh on 2 different machines - one using antigen the other doesn't. I realized that if I use the "typical .zshrc" example from antigens Readme#Usage, the robbyrussell theme looks different. In particular there's the '->' missing if I put the antigen theme robbyrussell definition before antigen apply. The theme looks the same as on my antigen less machine if I put it after apply.

**Comment by desyncr** [comment]
I'm gonna take a look later tonight.

**Comment by desyncr** [comment]
Related: https://github.com/zsh-users/antigen/issues/122

**Comment by Stefanqn** [comment]
Antigen v1.4.1

**Comment by desyncr** [comment]
Should be fixed on `develop`. Remember to clear your bundle cache:

    antigen reset

Thanks for reporting!
