### ISSUE TITLE
Missing prezto autoload functions

### ISSUE THREAD

**Issue by desyncr** [zsh-users/antigen#427]
As reported in gitter:

> \<module location\>/functions should be added to the fpath if it exists and each of the functions in there should be autoloaded...

**Comment by belak** [comment]
Fairly simple way to reproduce:

```
antigen use prezto
antigen bundle zsh-users/prezto modules/prompt
antigen apply

prompt agnoster # Or just look for a missing prompt_agnoster_setup
```

**Comment by desyncr** [comment]
Thanks a lot! Gonna look at it tonight!

**Comment by belak** [comment]
There's an experimental fix in #428

**Comment by desyncr** [comment]
@banyan #428 merged! Thanks for all the work!

**Comment by maximbaz** [comment]
Hey @desyncr and @belak, I'm experiencing seemingly the same problem, not sure if this is a new bug, regression or me doing something wrong.

The config is the following:

```
antigen use prezto
antigen bundle archive
antigen apply
```

This should load 3 functions: `lsarchive`, `archive` and `unarchive`. However, running `lsarchive test.zip` results in `zsh: permission denied: lsarchive`.

If I add `autoload -Uz lsarchive` and then try again, it will work.

```
❯ lsarchive test.zip
zsh: permission denied: lsarchive

❯ autoload -Uz lsarchive

❯ lsarchive test.zip
Archive:  test.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2017-12-07 19:29   test.txt
---------                     -------
        0                     1 file
```

As a workaround, I'm adding `autoload -Uz lsarchive archive unarchive` to my `antigenrc`, but shouldn't this be handled by antigen itself?

**Comment by belak** [comment]
@maximbaz In my own dotfiles, I use a combination of prezto and antigen. I use prezto for all prezto modules and antigen for everything else.

Here's an example:

```
zstyle ':prezto:*:*' color 'yes'
zstyle ':prezto:module:prompt' theme 'belak'
zstyle ':prezto:module:prompt' pwd-length 'short'
zstyle ':prezto:load' pmodule \
    'archive' \
    'prompt'

# Load the basic prezto library
antigen use prezto

# Load any external bundles we want
antigen bundle rupa/z z.sh

antigen apply
```

This lets prezto handle loading prezto modules (which will be more important once more functionality starts moving to the contrib repo) but uses antigen to load prezto core.

**Comment by maximbaz** [comment]
@desyncr could you reopen this issue? The bug is still valid, dirs are added to the fpath, but the functions still have to be autoloaded.

**Comment by belak** [comment]
The easiest/possibly best method would be to store the prezto modules which need to be loaded and just call pmodload on those... Then antigen can avoid digging into the details of how prezto modules are loaded.
