### ISSUE TITLE
Call post-install script for fzf

### ISSUE THREAD

**Issue by popstas** [zsh-users/antigen#434]
I'm trying to install [fzf](https://github.com/junegunn/fzf) with antigen.

Author of fzf recommends to install it in Vim with vim-plug:
```
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
```

Does antigen have analog of `do` for call install script after download bundle?

**Comment by desyncr** [comment]
@popstas Currently we don't support callback actions. Maybe in a future release as #339 is implemented.
