### ISSUE TITLE
antigen-selfupdate broken

### ISSUE THREAD

**Issue by miszr** [zsh-users/antigen#438]
Since commit 73a2d828241e3a4c988100371fdc822b4192277c the following lines of code in src/antigen.zsh have broken antigen-selfupdate:

The following changed:
`local _ANTIGEN_INSTALL_DIR="$(cd "$(dirname "$0")" && pwd)"`
To the following(_zsh version >= 4.3.7_):
`local _ANTIGEN_INSTALL_DIR=${0:A:h}`

Which breaks the following code in `src/commands/self-update.zsh`:
`if [[ ! ( -d .git || -f .git ) ]]; then`

The reason for this is that the new `_ANTIGEN_INSTALL_DIR` method resolves the symlink that links `antigen.zsh` to `bin/antigen.zsh`

This could be solved using:
`local _ANTIGEN_INSTALL_DIR=${0:A:h:h}`
Which would resolve the symlink and go back up one directory,

**Comment by desyncr** [comment]
I'll take a look! Thanks for reporting!

**Comment by miszr** [comment]
The fix that was implemented in f7d7c33954cc94e4208767b677c60fea7f543ac2 still has some flaws.

If the user is using a git clone of the antigen repository, then this will work good enough.
But if the user only downloaded the `antigen.zsh` file and placed it at an arbitrary location, then the `_ANTIGEN_INSTALL_DIR` will be incorrect(_zsh version >= 4.3.7_).

Example:
`/home/<user>/.config/antigen.zsh` will now result in `_ANTIGEN_INSTALL_DIR` being 
`/home/<user>`

If on the other hand, the uses the same structure as in the repository:
`/home/<user>/.config/antigen/bin/antigen.zsh` will result in a correct `_ANTIGEN_INSTALL_DIR` being `/home/<user>/.config/antigen`

**Comment by desyncr** [comment]
You're right, there are still some use case missing.

**Comment by desyncr** [comment]
@miszr There is a proposed fix in #442, if you could look at it and report any issue!
