### ISSUE TITLE
Antigen doesn't respect _ANTIGEN_COMPDUMP environment variable.

### ISSUE THREAD

**Issue by wonmin82** [zsh-users/antigen#452]
I have set _ANTIGEN_COMPDUMP in .zshenv, but zsh creates .zcompdump always in $ZDOTDIR.

**Comment by desyncr** [comment]
I'm gonna take a look. Thanks for reporting!

**Comment by desyncr** [comment]
Should be fixed in `develop`.

If you're running an stable version like `v1.4.x` you should probably wait for `v2.0.0` release instead of using `develop`.

**Comment by wonmin82** [comment]
Thanks for looking this.

I've confirmed this issue had fixed in `develop` branch.
