### ISSUE TITLE
fpath populated runtime vs statically

### ISSUE THREAD

**Issue by desyncr** [zsh-users/antigen#474]
See https://gist.github.com/desyncr/9196ebaf8fe4c410eba07675336e8285

This was reported on gitter and it affects Prezto theme loading.

Steps to reproduce:

1- antigen-reset
2- load a new shell

Shown behavior:

- Theme not loaded
- Error message regarding `prompt` usage

Expected behavior:

- Theme loaded correctly

Minimal `.zshrc`:

```
antigen use prezto
antigen bundle zsh-users/prezto modules/prompt
antigen apply

prompt agnoster

```

**Comment by belak** [comment]
I'm pretty sure this still triggers the issue, even with #475:

```
zstyle ':prezto:module:prompt' theme 'agnoster'
antigen use prezto
antigen bundle zsh-users/prezto modules/prompt
antigen apply
```

**Comment by desyncr** [comment]
Gonna test if it errors with `zstyle` *after* `antigen use prezto` otherwise it's a non-issue IMO, unless there's a common workflow that need just that.

**Comment by belak** [comment]
Yeah, it should error with zstyle after use prezto but before the bundle/apply.
