### ISSUE TITLE
What is the problem? How can I solve？

### ISSUE THREAD

**Issue by G-Bruin** [zsh-users/antigen#481]
![image](https://cloud.githubusercontent.com/assets/20853074/24826470/8d216348-1c69-11e7-8ac9-f22f5357cbc5.png)

**Comment by belak** [comment]
It looks like you're trying to use antigen with bash. However, antigen doesn't work with bash, it only works with zsh.

**Comment by desyncr** [comment]
@G-Bruin Exactly what @belak is describing. You should first install `zsh` and `git` then try again:

    $ apt-get install -y zsh git
    $ zsh
    $ source antigen.zsh

**Comment by G-Bruin** [comment]
thanks!
