### ISSUE TITLE
init.zsh regenerates with references to pre-2.0 directories

### ISSUE THREAD

**Issue by john-kurkowski** [zsh-users/antigen#485]
After installing 2.0.0, I get an error with every new terminal.

```zsh
/Users/John/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/fasd/fasd.plugin.zsh:4: no such file or directory: /Users/John/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git/cache//fasd-init-cache
/Users/John/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/fasd/fasd.plugin.zsh:source:6: no such file or directory: /Users/John/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git/cache//fasd-init-cache
```

Where could it be getting that path from? The only reference I could find is in .antigen/init.zsh. Its tail:

```zsh
_ANTIGEN_CACHE_LOADED=true ANTIGEN_CACHE_VERSION='v2.0.0'
ZSH="/Users/John/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git" ZSH_CACHE_DIR="/Users/John/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git/cache/"
#-- END ZCACHE GENERATED FILE
```

If I clear .antigen/init.zsh, it keeps regenerating with the old directory structure, .antigen/repos/stuff-with-SLASH-in-them. In 2.0.0, the repos/ folder is empty (in favor of bundles/ I think). Not sure what still thinks repos/ is valid.

**Comment by desyncr** [comment]
It seems `ZSH` and `ZSH_CACHE_DIR` are set somewhere else. Could you try with a minimal .zshrc configuration?

**Comment by john-kurkowski** [comment]
It does look like they originally came from Antigen source ([1.4.1](https://github.com/zsh-users/antigen/blob/v1.4.1/src/lib/use-oh-my-zsh.zsh#L3)). I couldn't figure out what kept carrying them over to new terminals. I flailed around a bit trying to get them to not carry over. Somehow I managed. Then, deleting .antigen/init.zsh* instead of just .antigen/init.zsh deleted one additional cache file. Now, these 2 env vars are set correctly!

```zsh
➜  ~ echo $ZSH
/Users/John/.antigen/bundles/robbyrussell/oh-my-zsh
➜  ~ echo $ZSH_CACHE_DIR
/Users/John/.antigen/bundles/robbyrussell/oh-my-zsh/cache/
```

Unfortunately an error message similar to my original one persists.

```zsh
/Users/John/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/fasd/fasd.plugin.zsh:4: permission denied: /fasd-init-cache
/Users/John/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/fasd/fasd.plugin.zsh:source:6: no such file or directory: /fasd-init-cache
```

Looks like `$ZSH_CACHE_DIR` is no longer set in time for the fasd plugin to use it.

**Comment by desyncr** [comment]
It's an issue in the [cache lib](https://github.com/zsh-users/antigen/blob/develop/src/lib/zcache.zsh#L131). As a workaround do set `ZSH` and `ZSH_CACHE_DIR` manually before sourcing Antigen.

I'm gonna work on a fix. Probably ready for `v2.0.1`.

Thanks for reporting!

**Comment by desyncr** [comment]
Fixed in `develop` branch. Ready for `v2.0.1`.

**Comment by john-kurkowski** [comment]
Thank you!
