### ISSUE TITLE
Cannot clone a bundle from an SSH repo with custom port

### ISSUE THREAD

**Issue by mgryszko** [zsh-users/antigen#490]
When trying to add a bundle in Antigen 2.0.0 with SSH Git protocol and custom port:

```
antigen bundle ssh://git@example.com:10022/group/repo.git
```

followed by `antigen reset`, I get this error in the log:

```
Cloning into '/Users/mgryszko/.antigen/bundles//git-example.com:10022-group-repo.git'...
fatal: No path specified. See 'man git-pull' for valid url syntax
```

The Git repository is an internal company repository managed by Gitlab. I removed the URL and the actual repo name due to confidentiality issues.

This was working in 1.4.1 so it's a regression bug for me.

**Comment by oli206** [comment]
Same issue here

**Comment by desyncr** [comment]
I'm gonna look for a fix! Thank's for reporting!

**Comment by mgryszko** [comment]
Can you have a look at #491 too for 2.0.1 milestone. Actually this issue resulted from the other one - instead of loading a bundle from a local filesystem I tried to load the bundle from Gitlab.

**Comment by desyncr** [comment]
Work in progress [here](https://github.com/zsh-users/antigen/pull/492) if you can take a look at it.

**Comment by desyncr** [comment]
@mgryszko  btw you may try

```
antigen bundle --url ssh://git@example.com:10022/group/repo.git
```

as a workaround.

**Comment by desyncr** [comment]
Available in `develop`. Ready for `2.0.1`.

**Comment by oli206** [comment]
That was fast, thanks! Will give it a try

**Comment by mgryszko** [comment]
Confirmed, working as expected
