### ISSUE TITLE
Local no-clone bundle is not loaded after antigen reset

### ISSUE THREAD

**Issue by mgryszko** [zsh-users/antigen#491]
Antigen 2.0.0. I have a local bundle under continuous development. It's added to Antigen in this way:
```
antigen bundle /Users/mgryszko/my-zsh-plugins --no-local-clone
```

To activate it, I perform `antigen reset` in a terminal. I get the message `Done. Please open a new shell to see the changes.`. Then I open a new shell; the bundle is loaded as expected.

However, when I open yet another shell, the bundle is not loaded anymore.

This configuration was working in Antigen 1.4.1, so this is a regression bug for me.

**Comment by desyncr** [comment]
Thanks I'm gonna take a look today.

**Comment by desyncr** [comment]
You can take a look [here](https://github.com/zsh-users/antigen/pull/493). Let me know if you see anything wrong with it.

**Comment by desyncr** [comment]
It's available on `develop`. Ready for `2.0.0`.

**Comment by mgryszko** [comment]
Confirmed, working as expected
