### ISSUE TITLE
antigen theme <any-theme> keeps changing my directory

### ISSUE THREAD

**Issue by AndydeCleyre** [zsh-users/antigen#494]
Each time I run `antigen theme <anytheme>`, I get booted between the current directory and the home directory. For example:

![image](https://cloud.githubusercontent.com/assets/1787385/24976097/1fbc70a6-1f96-11e7-82a8-f61d4b0b929b.png)

antigen `v2.0.0.r0.g5a70b51`

**Comment by desyncr** [comment]
Thanks for reporting. I'm gonna take a look at this.

**Comment by desyncr** [comment]
Should be fixes in https://github.com/zsh-users/antigen/pull/495 if you want to take a look.

**Comment by desyncr** [comment]
Should be fixed in `develop`. Ready for `2.0.1`.
