### ISSUE TITLE
selfupdate without a git clone

### ISSUE THREAD

**Issue by Fuzen-py** [zsh-users/antigen#496]
It is possible to use selfupdate without cloning by using downloading a file. it would be nice to see this ability added.

**Comment by Eloo** [comment]
You can simply add somethink like that to your .zshrc file
`# Override antigen-selfupdate
function antigen-selfupdate(){
	wget 'https://raw.githubusercontent.com/zsh-users/antigen/develop/bin/antigen.zsh' -O ~/dotfiles/antigen.zsh.tmp 
	mv ~/dotfiles/antigen.zsh.tmp ~/dotfiles/antigen.zsh
	source ~/dotfiles/antigen.zsh
}`

**Comment by Fuzen-py** [comment]
Oh, thank you [that](https://github.com/Fuzen-py/ZSHFiles/blob/master/.zshrc#L79-L83) was much simpler than what i had done [earlier](https://github.com/Fuzen-py/antigen/commit/b6c1b2b80676befd10b5e0ecec0828524a9945fb) 😄

**Comment by desyncr** [comment]
Additional I would do two things:

- Use `git.io/antigen-nightly` as it is our canonical url for `develop` builds
- Create a gist or github repo to be able to bundle it (ex, `antigen bundle desyncr/antigen-selfupdater`)

**Comment by Fuzen-py** [comment]
Wouldn't this require antigen to store the path for the script?

**Comment by desyncr** [comment]
You could use `$_ANTIGEN_INSTALL_DIR` which works regardless of installation method (git clone, curl/wget, brew etc)

**Comment by Fuzen-py** [comment]
This doesn't include the exact path of the script. It might not be named antigen.zsh

**Comment by desyncr** [comment]
It is the exact path of Antigen. If you rename it is up to you.
