### ISSUE TITLE
Why does my shell always starts with exit code != 0?

### ISSUE THREAD

**Issue by rfgamaral** [zsh-users/antigen#507]
After solving #500 I now have another issue with my Antigen installation on Cygwin.

I have cloned antigen repo to ` /usr/local/bin/antigen` and this is my `.zshrc`configuration:

```zsh
source /usr/local/bin/antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundle command-not-found
antigen bundle common-aliases
antigen bundle extract
antigen bundle git
antigen bundle git-flow
antigen bundle gradle
antigen bundle heroku
antigen bundle history

antigen theme robbyrussell

antigen apply
```

The robbyrussell theme has a simple prompt like `➜  ~`. The arrow will be green when the last command executed successfully and red when unsuccessful.

Every time I launch Cygwin (Windows shortcut: `C:\Cygwin64\bin\mintty.exe -i /Cygwin-Terminal.ico -`), the  `➜` arrow is colored red:

![image](https://cloud.githubusercontent.com/assets/96476/25083960/0509ebb6-2352-11e7-80eb-899bc3db6a51.png)

I always end my Cygwin session by pressing `Ctrl+D`, but I also tried to run `exit` on the terminal.

Am I doing something wrong?

**Comment by desyncr** [comment]
This is a pending issue. I have to take a look at this.

**Comment by desyncr** [comment]
btw this was reported [here](https://github.com/zsh-users/antigen/issues/488#issuecomment-293489244) and it's an Antigen issue, nothing wrong with your configuration or installation.

**Comment by rfgamaral** [comment]
Great :)

Should we close this one then?

**Comment by desyncr** [comment]
No, it's good. I should have had created an specific issue for this. It will make easier for others experiencing the same issue to find it. 👍

**Comment by desyncr** [comment]
Should be fixes in #508. Target release `2.0.2`, due by April 23, 2017.

**Comment by rfgamaral** [comment]
@desyncr Any way I can get this right now instead of waiting for April 23?

**Comment by desyncr** [comment]
You can get our nightly releases from git.io/antigen-nightly

DC*
