### ISSUE TITLE
`antigen-theme` command fails on Cygwin

### ISSUE THREAD

**Issue by rfgamaral** [zsh-users/antigen#516]
I'm using Zsh on Cygwin and I have installed through the Git method but I'm using the `develop` branch instead of `master`. I've cleaned up my `~/.antigen` folder and restarted my shell. But now I got this:

```
Installing robbyrussell/oh-my-zsh@master... Done. Took 11s.
(eval):3: command not found: ^M
-zcache-generate-cache:zcompile:78: can't read file: /cygdrive/c/Users/Amaral/.antigen/init.zsh
```

This is my `.zshrc` file:

```
export EDITOR=nano
export HISTFILE=~/.zhistory

source /usr/local/bin/antigen/antigen.zsh

antigen use oh-my-zsh
antigen theme robbyrussell
antigen apply
```

**Comment by desyncr** [comment]
I believe I have seen a similar issue way back. You'll need to clear your configs of `^M` characters.

**Comment by rfgamaral** [comment]
What exactly are "my configs"?

**Comment by desyncr** [comment]
`.zshrc`, open it up in a code editor/vim/etc which shows invisible characters. Check if there is a `^M` or similar.

**Comment by rfgamaral** [comment]
There are none on my `.zshrc` file :(

**Comment by rfgamaral** [comment]
I pinpointed this issue to `antigen theme` command:

```
Amaral@NAZBOX:~% antigen theme refined
(eval):106: parse error near `\n'
antigen theme robbyrussell
(eval):3: command not found: ^M
antigen theme avit
(eval):27: parse error near `elif'
```

Something's wrong here...

**Comment by desyncr** [comment]
Try with:

    antigen bundle robbyrussell/oh-my-zsh refined.zsh-theme

Themes are handled in a specific way to make it work in interactive mode as well as from cache; this is due to how some (oh-my-zsh) themes are built. See [here](https://github.com/bhilburn/powerlevel9k/pull/38#issuecomment-118385844).

BTW you can use the same command for any other theme:

        antigen bundle robbyrussell/oh-my-zsh {theme-name}.zsh-theme

**Comment by rfgamaral** [comment]
@desyncr Didn't work, I got this:

> Antigen: Failed to load plugin.

**Comment by desyncr** [comment]
My bad:

    antigen bundle robbyrussell/oh-my-zsh themes/refined.zsh-theme

**Comment by rfgamaral** [comment]
I got no errors no but my shell prompt didn't theme/colors didn't change at all.

**Comment by rfgamaral** [comment]
It partially worked now... The theme doesn't look like the real theme.

This is how it should look:

![image](https://cloud.githubusercontent.com/assets/96476/25245785/7da99046-25fd-11e7-9f52-df3bdf5c2681.png)

But this is how it looks now:

![image](https://cloud.githubusercontent.com/assets/96476/25245816/a2e29e8e-25fd-11e7-8bbb-64070349f6ae.png)

Note that I've changed the theme to `robbyrussell` with `antigen bundle robbyrussell/oh-my-zsh themes/robbyrussell.zsh-theme`.

**Comment by desyncr** [comment]
That behaviour is due to https://github.com/bhilburn/powerlevel9k/pull/38#issuecomment-118385844. Some OMZ themes work correctly, some others do not.

`antigen-theme` command prevents it for happening. In your case `antigen-theme` fails for other reason unrelated (something with how `sed` works on Cygwin/windows/etc).

I'll have to take a closer look at the issue with `antigen-theme` on Cygwin.

**Comment by desyncr** [comment]
Updated issue title to match the issue.

**Comment by rfgamaral** [comment]
The weird thing to me is that I get those "parse error" and "command not found" messages but if i close the shell and reopen it, everything is fine and the theme actually displays correctly.

**Comment by desyncr** [comment]
I see. Good info, it's the generated cache the issue. Gonna try to reproduce on a VM.

**Comment by desyncr** [comment]
Seems to work correctly on a test VM. Cygwin 2.8.0-1.

![screenshot from 2017-04-22 01-33-08](https://cloud.githubusercontent.com/assets/1857707/25301367/b2f50c2c-26fb-11e7-868d-f0a37ac3a8ee.png)

**Comment by rfgamaral** [comment]
I think you're missing the arrow symbol in the robbyrussell theme.

**Comment by desyncr** [comment]
Indeed. Those are not issue with Antigen but with cygwin/zsh install which I particularly don't care about as I don't use it.

**Comment by rfgamaral** [comment]
I understand... But thing is, this didn't use to happen a few days ago, everything was fine. Not sure what why this is happening now...
