### ISSUE TITLE
Antigen update points to incorrect path for older version 

### ISSUE THREAD

**Issue by gilbertwyw** [zsh-users/antigen#517]
I got the following message after `antigen update` on macOS 10.12.4 with Zsh 5.3.1: 

```
antigen:source:1: no such file or directory: /usr/local/Cellar/antigen/2.0.0/share/antigen/antigen.zsh
```
I'm currently using Homebrew's version of 2.0.1 and here's the output of `which -a antigen`:
```
antigen () {
        [[ "$ZSH_EVAL_CONTEXT" =~ "toplevel:*" || "$ZSH_EVAL_CONTEXT" =~ "cmdarg:*" ]] && source "/usr/local/Cellar/antigen/2.0.0/share/antigen/antigen.zsh" && eval antigen $@
}
```
The output of `brew list antigen`:
```
/usr/local/Cellar/antigen/2.0.1/share/antigen/antigen.zsh
```

And this is how I configure antigen: 

```
source $(brew --prefix)/share/antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundle brew
antigen bundle brew-cask
antigen bundle common-aliases
antigen bundle git

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions

antigen bundle mafredri/zsh-async
antigen bundle sindresorhus/pure

antigen apply
```

Any idea? Thanks.

**Comment by desyncr** [comment]
You should do `antigen reset` or remove cache manually by doing `rm $ADOTDIR/init.zsh` (usually `~/.antigen/init.zsh`.

What happened is that the generated cached pointed to an older installation. (Currently it saves the cache version/antigen version but it doesn't check it in order to avoid this kind of issues).

**Comment by gilbertwyw** [comment]
Thanks for your prompt reply.

FYI, I `rm ~/.antigen/init.zsh` and open a shell and it *WORKS* again

**Comment by geekifier** [comment]
Just FYI, when I encountered this issue, `antigen reset` produced the same error message. So the correct solution is to `rm $ADOTDIR/init.zsh`, as was also suggested.
