### ISSUE TITLE
emit error: `_arguments:451: _vim_files: function definition file not found` when starting vim

### ISSUE THREAD

**Issue by MoonBall** [zsh-users/antigen#528]
### Environments
- vim version: 8.0
- os: macOS 10.12.4
- zsh version: zsh 5.3.1 (x86_64-apple-darwin16.3.0)
- antigen version: 2.0.2

### .zshrc file
`
source ~/.zsh/antigen.zsh
`
### Steps
1. `cd ~`, there is .zshrc in user home directory
2. type `vim .zshr` and type tab, expect completing the command to `vim .zshrc`. But
3. emit error `_arguments:451: _vim_files: function definition file not found`

**Comment by desyncr** [comment]
Works on my side. It could be that your env is missing a path to fpath:
```
% echo $fpath
/usr/local/share/zsh/site-functions /usr/local/Cellar/zsh/5.3/share/zsh/functions
```

Another option is that you've an old zcompdump file. You could try:

    antigen reset

Or simply `rm ~/.antigen/.zcomp*`.

**Comment by MoonBall** [comment]
In `~` directory, there are 3 `.zcomp*` file.
`
-rw-r--r--    1 gangc  staff  154530  5  5 02:16 .zcompdump
-rw-r--r--    1 gangc  staff   38593  5  4 00:31 .zcompdump-陈刚的MacBook Pro-5.2
-rw-r--r--    1 gangc  staff   40611  5  4 00:31 .zcompdump-陈刚的MacBook Pro-5.3.1
`
It works after delete them.

**Comment by DanNordness** [comment]
I'm having this same issue and neither running `antigen reset` nor `rm ~/.zcomp* ~/.antigen/.zcomp*` seems to fix it for me.

**Comment by fazlearefin** [comment]
After you run `antigen reset`, you need to open a new terminal.

**Comment by kylezhang** [comment]
I deleted `rm ~/.zcomp* `, but it still does not work.

**Comment by fazlearefin** [comment]
@kylezhang Just run

`antigen reset`

And then open a new terminal. No need to manually delete any files.

**Comment by patrick-bohan** [comment]
For those that might run into this situation, I am running [zplug](https://github.com/zplug/zplug) and had included [lib/compfix.zsh](https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/compfix.zsh) directly in my .zshrc using `zplug "lib/compfix", from:oh-my-zsh`   (since zplug does not automatically load everything from OMZ).

Removing the various `.zcompdump*` files did nothing. The error only went away when I removed that plugin.

I hope this helps someone out there.

**Comment by wqycsu** [comment]
If `rm .zcomdump* & exec zsh` does not work for you, please check do you install zplug or not?

**Comment by sebastian2696** [comment]
@wqycsu that solution works. The zcomdump* file is inside zplug folder, for those looking for it

**Comment by houpfchn** [comment]
I also encountered the same problem as you do. You can do this：
rm -rf ~/.zcompdump-*
exec zsh
