### ISSUE TITLE
sort: cannot read: 'LESS_TERMCAP_mb='$'\033''[1;31m': No such file or directory

### ISSUE THREAD

**Issue by stevenwalton** [zsh-users/antigen#530]
So after a reinstall of Ubuntu 16.04 (Friday) I of course start my zsh and get my config going. I used my old zshrc file (see below) and found that I am having errors with man pages. When I type `man <anything>` I get the above message. I should also mention as soon as I move to bash I do not have this problem.

I did find that as soon as I remove `source "$HOME/.antigen/antigen.zsh"` then things work perfectly and I can just do the `export LESS_TERMCAP_x` commands and get the coloured man pages. 
```
# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

export PATH=$HOME/bin:/usr/local/bin:$PATH
source $ZSH/oh-my-zsh.sh
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename "$HOME/.zshrc"
autoload -Uz compinit
compinit
if [[ -r ~/.local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh ]]; then
       source ~/.local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh
fi
# End of lines added by compinstall
#[ -e "${HOME}/.zsh_aliases" ] && source "${HOME}/.zsh_aliases"
#[ -e "${HOME}/.zshrc_local" ] && source "${HOME}/.zshrc_local"

# Alieses
alias ls='ls --color=auto'
alias la='ls -a'
alias vi='vim'
alias top='htop'
# Tmux doesn't like to recognize 256 colouring, so let's force it
alias tmux='tmux -2'
alias df='df -h'
alias log='git log --graph --oneline --decorate'
alias grep='grep --color=always'
alias g++='/usr/bin/g++ -std=c++11'
alias h5c++='/usr/bin/h5c++ -std=c++11'
alias env='env | sort'

source "$HOME/.antigen/antigen.zsh"
antigen use oh-my-zsh
#
# # bundles from oh-my-zsh
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle screen
antigen bundle colored-man-pages

antigen theme jdavis/zsh-files themes/jdavis
antigen apply

export EDITOR="vim"
```
Some other stuff that might be relevant from googling this problem.
```
[ steven.walton ] [~] > echo $PAGER                                                                                                                                                  
less
[ steven.walton ] [~] > file /usr/bin/man                                                                                                                                           
/usr/bin/man: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=dceb4fb7122094ee8547be2d8b4da34225e6f80a, stripped
[ steven.walton ] [~] > echo $MANPAGER 

```
Using `grep -R "LESS_TERMCAP" ~/` (where my antigen and oh-my-zsh clones are) I only find relevant references to 
```
./.antigen/bundles/jdavis/zsh-files/colors/config.zsh
./.antigen/bundles/robbyrussell/oh-my-zsh/plugins/colored-man-pages/colored-man-pages.plugin.zsh
./.oh-my-zsh/plugins/colored-man-pages/colored-man-pages.plugin.zsh
```

**Comment by desyncr** [comment]
Thanks for reporting. I'm gonna give it a look tonight.

**Comment by stevenwalton** [comment]
I was wondering if there was an update. If you could at least reproduce my bug. If not I can provide more information.

**Comment by desyncr** [comment]
Hey there @stevenwalton Unfortunately I wasn't able to further investigate it. Been behind schedule for awhile.

Will try to check it tonight.

**Comment by desyncr** [comment]
@stevenwalton After taking a quick look it seems it's an issue between your config and colored-man-pages plugin due to `env` alias (`env | sort`) and colored-man-pages plugin [internals](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/colored-man-pages/colored-man-pages.plugin.zsh#L20). I believe colored-man-pages should use `builtin env` or `\env` to avoid alias conflicting.

**Comment by desyncr** [comment]
Closing for now. Comment if the issue still persists.
