### ISSUE TITLE
Themes don't work

### ISSUE THREAD

**Issue by chkl** [zsh-users/antigen#544]
Hi,
first of all, I haven't used antigen before, so this might also be rather a documentation problem.

I followed the installation instructions (dowloading `~/antigen.zsh`). My `.zshrc` looks like this:
```
source /home/klingerc/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle heroku
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# Load the theme.
antigen theme robbyrussell

# Tell Antigen that you're done.
antigen apply


# Customize to your needs...
path=(
        ~/.local/bin
        ~/.local/bin/android-studio/bin
        $path
)
export path
```
which is just a copy and paste from the installation instructions.

When I open a new terminal now (konsole or gnome-terminal) my prompt looks like this:
```
$(build_prompt) 
```
It seems like the variable `$build_prompt` does not get extended.

**Comment by desyncr** [comment]
@chkl Hey there! First, thanks for using Antigen. Second it all seems OK, I'll give it a quick try locally and see what's going on!

**Comment by desyncr** [comment]
Locally it works as expected. I'm wondering if you may have a cached config. Try the following:

    antigen reset

Best regards!

**Comment by chkl** [comment]
`antigen reset` fixed it. Thanks!
