### ISSUE TITLE
Theme caching breaking dynamic zshrc

### ISSUE THREAD

**Issue by robobenklein** [zsh-users/antigen#546]
There's some weird things going on with themes and theme loading.

Without antigen:
![no-antigen](https://user-images.githubusercontent.com/5423266/27153432-6940c050-511f-11e7-9991-2bef8c772427.gif)

With antigen:
![with-antigen](https://user-images.githubusercontent.com/5423266/27153442-743652fe-511f-11e7-9111-32d81cd0aede.gif)

Both of these gifs are using the _exact same_ .zshrc, which loads antigen only if it's found:
```zsh
# Default in case we don't know if terminal has powerline fonts.
ZSH_THEME="fishy"
case "$TERM_PROGRAM" in
  'guake.main'|\
  'terminator'|\
  'iTerm.app'|\
  'gnome-terminal-server'|\
  'tmux'|\
  '0') # for some reason we get zero from SSH connections
    ZSH_THEME="agnoster"
    ;;
  default)
    ZSH_THEME="fishy"
    ;;
esac
```
And then loading antigen:
```zsh
# If ~/.antigen, then use that instead of oh-my-zsh
if [ -d $HOME/.antigen ]; then
  source $HOME/.antigen/antigen.zsh
  antigen use oh-my-zsh
  for plugin in $antigenplugins; do
    antigen bundle "$plugin"
  done
  antigen theme $ZSH_THEME
  antigen apply
  # Remove paths that start with $HOME/.antigen/
  path=( ${path%$HOME/.antigen/*} )
else
  # Otherwise use oh-my-zsh
  source $ZSH/oh-my-zsh.sh
fi
```
Full zshrc: https://github.com/robobenklein/configs/blob/08796224a7c1d3e814ab240287a31ed8e051d455/zsh/.zshrc

I'm trying to make this work so that my .zshrc becomes as portable as possible, including being placed in terminals without fonts like Ubuntu's vttys, for which I would want a different theme.  
The theme switching strategy I have works with oh-my-zsh, however, even though I call `antigen theme $ZSH_THEME` every zshrc, and the env var is set correctly, Antigen still doesn't update the theme when started.

**Comment by desyncr** [comment]
Hey there @robobenklein.

This happened before. By design Antigen aims for static loading of plugins, this way you get really small start up times.
This is achieved by building caches, which may interfere with dynamic plugin loading. For dynamic loading you got a couple of options:

1- Disable cache (`ANTIGEN_CACHE=false`)
2- Configure cache path for each instance (See links below)

There are examples and further description [here](https://github.com/zsh-users/antigen/wiki/Commands#antigen-theme). Also you may take a look at the [Commands](https://github.com/zsh-users/antigen/wiki/Configuration) wiki page.

**Comment by robobenklein** [comment]
That solves my problem, but I still don't understand how a one-off theme switch works differently from the same 'theme' command, but just stored in the .zshrc. How does the live session command switch properly if the same command in the startup script hits the cache instead?

**Comment by desyncr** [comment]
Antigen differentiates between interactive and non-interactive sessions. Interactive shell doesn't hit or modify cache, this way you can still pay with Antigen (see [Show off](https://github.com/zsh-users/antigen/wiki/Show-off) section) without having your changes being persisted.

**Comment by robobenklein** [comment]
No further issues on my Linux box, however having different issues with zcompdump on OSX...

**Comment by desyncr** [comment]
Feel free to open up a new issue for those OSX issues.
