### ISSUE TITLE
Parallel install's message can be confusing

### ISSUE THREAD

**Issue by desyncr** [zsh-users/antigen#548]
As described [here](https://gitter.im/antigen-zsh/develop?at=5942b95a31f589c64fae0456).

When installing multiple bundles from the same repository (ex. omz) "install message" looks as follows:

    Installing robbyrussell/oh-my-zsh!...
    Installing robbyrussell/oh-my-zsh!...
    Installing robbyrussell/oh-my-zsh!...
    Installing robbyrussell/oh-my-zsh!...

One option is to show path in such cases:

    Installing robbyrussell/oh-my-zsh~command-not-found!...
    Installing robbyrussell/oh-my-zsh~docker!...
    Installing robbyrussell/oh-my-zsh~extract!...

A second option is to only show a single message for each repository (rather than for each bundle).

**Comment by dein0s** [comment]
Also, I've 22 bundles in [config](https://github.com/dein0s/dotfiles/blob/master/shells/zsh/antigenrc.dotfile) + theme (23), but for some reason I see only 9 "installing" messages:
```bash
Installing robbyrussell/oh-my-zsh!...
Installing robbyrussell/oh-my-zsh!...
Installing robbyrussell/oh-my-zsh!...
Installing robbyrussell/oh-my-zsh!...
Installing soimort/translate-shell@develop!...
Installing djui/alias-tips!...
Installing zsh-users/zsh-autosuggestions!...
Installing fcambus/ansiweather!...
Installing dein0s/dotfiles!...
```

**Comment by desyncr** [comment]
It was designed in a way that it only shows "Installing" message for each repository. Now I'm considering showing a message for each bundle, as to not cause this confusion.
