### ISSUE TITLE
Themes only load if .zshrc is sourced

### ISSUE THREAD

**Issue by jeffmartinxyz** [zsh-users/antigen#551]
I'm trying to use the agnoster theme provided from oh my zsh unsuccessfully. It does not load using the config attached below, however, it does load if I `source .zshrc`.

```
# settings
HISTFILE=~/.histfile
HISTSIZE=1000000000
SAVEHIST=1000000000
setopt appendhistory autocd extendedglob notify
unsetopt beep nomatch
bindkey -v
zstyle :compinstall filename '/home/jm/.zshrc'
autoload -Uz compinit
compinit

# antigen
source /usr/share/zsh/share/antigen.zsh
antigen use oh-my-zsh
antigen bundle zsh-users/zsh-syntax-highlighting
antigen theme agnoster
antigen apply

# aliases
alias install='yaourt -S'
alias remove='yaourt -R'
alias update='sudo pacman -Syu'
```

**Comment by desyncr** [comment]
A minimal working configuration (using zsh `zsh 5.3 (x86_64-apple-darwin14.5.0)`, antigen `develop`)


```

$ cat ~/.zshrc
source /path/to/antigen.zsh
antigen use oh-my-zsh
antigen bundle zsh-users/zsh-syntax-highlighting
antigen theme agnoster
antigen apply
```

**Comment by K5HV** [comment]
I've got this same issue on ArchLinux (zsh 5.3.1 (x86_64-unknown-linux-gnu)) with antigen installed from AUR (antigen-git v2.2.0.r2.g47a99ad-1).

```
k5hv@e6430:~% cat .zshrc
source /usr/share/zsh/share/antigen.zsh
antigen bundle zsh-users/zsh-syntax-highlighting
antigen theme clean
antigen apply
k5hv@e6430:~% . ~/.zshrc 
k5hv:~/ $                                                            [23:04:59]
```
 It's seems that zsh-syntax-highlighting boundle also wasn't loaded.

**Comment by jeffmio** [comment]
I should have included this previously, but I'm running the same setup as @K5HV

**Comment by K5HV** [comment]
It seems that removing my .antigen and resource my .zshrc fixed the issue

**Comment by Falieson** [comment]
I used the .zshrc provided in the readme.md, changed the theme to steeef and reloaded my zsh and nothing changed. running
`source .zshrc` fixed the issue

**Comment by desyncr** [comment]
The issue comes from Antigen not being able to determine configuration changes (see [here](https://github.com/zsh-users/antigen/wiki/Troubleshooting#my-bundles-wont-update)).

Doing `antigen-reset` should fix it.

**Comment by Probotect0r** [comment]
Hey, I am having a similar issue. This is what my .zshrc has:
```
source ~/antigen.zsh

antigen use oh-my-zsh

antigen bundle git 
antigen bundle nvm 
antigen bundle wd
antigen bundle tomsquest/nvm-auto-use.zsh

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen theme agnoster
antigen apply

# User configuration
bindkey '^ ' autosuggest-execute

# This loads nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  

# Source .profile so you get login configs as well
source ~/.aliases.sh
source ~/.profile

# This loads nvm bash_completion
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
```
My theme doesn't get loaded in new shells unless I run `antigen theme agnoster` or `. ~/.zshrc`.
If I run `antigen-reset`, and then open a new shell, the theme is loaded in that shell. But all other shells opened after that don't have the theme loaded.

**Comment by Probotect0r** [comment]
Ok something happened and its working fine now lol
