### ISSUE TITLE
antigen theme issue?

### ISSUE THREAD

**Issue by sthtodo** [zsh-users/antigen#555]
MacOS 10.12.5
iTerm 3.0.15
zsh 5.2
antigen 79782288ef286fda8b48f1b3a82aa6f9bdf16864

using git method that cloned the repo to my local. 
setup .zshrc with example
```
source $HOME/dotfiles/antigen/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle heroku
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# Load the theme.
antigen theme robbyrussell

# Tell Antigen that you're done.
antigen apply
```

restart iTerm, and it's stopping in Installing 

`Installing robbyrussell/oh-my-zsh!...
Installing zsh-users/zsh-syntax-highlighting!...`

removed `antigen theme robbyrussell` and `rm -rf ~/.antigen`, terminal is working but without theme but don't think any bundles are working.

**Comment by desyncr** [comment]
@sthtodo It's an issue with latest release, specifically [this issue](https://github.com/zsh-users/antigen/pull/552).

Locally I could interactively use it without issue, but I'm gonna take a deeper look.

Thanks for reporting.

**Comment by desyncr** [comment]
Same config as yours:

```
➜  ~ antigen list
robbyrussell/oh-my-zsh ~ lib @ master
robbyrussell/oh-my-zsh ~ plugins/git @ master
robbyrussell/oh-my-zsh ~ plugins/heroku @ master
robbyrussell/oh-my-zsh ~ plugins/pip @ master
robbyrussell/oh-my-zsh ~ plugins/lein @ master
robbyrussell/oh-my-zsh ~ plugins/command-not-found @ master
zsh-users/zsh-syntax-highlighting @ master
robbyrussell/oh-my-zsh ~ themes/robbyrussell.zsh-theme @ master
➜  ~ zsh --version
zsh 5.3 (x86_64-apple-darwin14.5.0)
➜  ~
```

**Comment by sthtodo** [comment]
No worries, I am use stable version now that comes from curl method.

**Comment by sthtodo** [comment]
tried git method, and it works now, thanks!
added into submodule of my dotfiles.

**Comment by desyncr** [comment]
@sthtodo Awesome! Let us know of any issue if you have!
