### ISSUE TITLE
Link official Debian package instead of openSUSE

### ISSUE THREAD

**Issue by fladi** [zsh-users/antigen#559]
_Full disclosure: I'm the maintainer for the Debian zsh-antigen package._

Would it be possible to link to the [official Debian package](https://packages.debian.org/source/stretch/zsh-antigen) instead of the one from openSUSE build service?

It is not the latest version (1.3.4) in the stable release but I try to keep it up to date in the unstable branch of Debian.

Installation is as easy as running `sudo apt install zsh-antigen`.

**Comment by desyncr** [comment]
Though it was being unmaintained. Gonna add it to the README together with openSUSE build service.

Thanks for the work maintaining the package!

**Comment by desyncr** [comment]
Done. Updated README.md, added wiki page for Installation options, including Debian package. Thanks for the work maintaining it!

This is gonna be release tomorrow as v2.2.1
