### ISSUE TITLE
Loading themes: eval means I can't find ancillary files.

### ISSUE THREAD

**Issue by docwhat** [zsh-users/antigen#581]
I'm working on a prompt theme that needs additional resources from its source directory.

For other plugin systems I can just use `${(%):-%x}` to get the source file and work from there, but because themes are `eval`ed I can't do that.

I tried reading the wiki but it seems to be out-of-date, since it talks about `source`ing instead of `eval`ing.

At the moment, it looks like I'll have to either ask the user for the installation path or resort to something like this:

``` zsh
if [[ "${(%):-%N}" == '(eval)' ]] && [[ "$0" == '-antigen-load' ]] && [[ -d "${url}" ]]; then
  print -P "%F{yellow}Detected antigen! Using workaround due to (eval).%f"
  installation_directory=${url}
fi
```

Alternatively, is there some benefit to using [this code](https://github.com/zsh-users/antigen/blob/master/bin/antigen.zsh#L603-L605) to do an eval instead of just using `source`?

``` zsh
eval "$(cat $line | sed -Ee '/\{$/,/^\}/!{
       s/^local //
   }');"
```

Firing up `cat` and `sed` is slow (especially on Windows and spinning disks) and the substitution seems like it wouldn't work in all cases, though it does nothing to my theme.

Is there a more Antigen friendly for me to detect where my files are or is this a bug in Antigen?

**Comment by desyncr** [comment]
That particular code make themes work with Antigen when they define `locals` globally. See https://github.com/zsh-users/antigen/issues/122. Doesn't `${0:A:h}` works?

**Comment by docwhat** [comment]
No.  `$0` is the antigen function. Eg `-antigen-load`

**Comment by desyncr** [comment]
A bit of manual testing gave me this:

antigen.zsh
```
        if [[ "$btype" == "theme" ]]; then
          echo $0
          pushd "${line:A:h}" > /dev/null
```

geometry.zsh-theme
```
  GEOMETRY_ROOT=${0:A:h}
  echo $GEOMETRY_ROOT
  echo ${(%):-%N}
```

```
$ antigen theme fribmendes/geometry
-antigen-load
/Users/user/.antigen/bundles/fribmendes/geometry
(eval)

```

**Comment by docwhat** [comment]
So my theme is meant to work with more than Antigen... it is located outside the `~/.antigen/` directory.  I should have included an example `.zshrc`:

``` zsh
source ~/antigen/antigen.zsh

antigen theme "${HOME}/src/my-prompt-theme" my-prompt --no-local-clone
antigen apply
```

Oh, I see why your usage of `${0}` appears to work (which it only does in this case):

- `${0}` is `-antigen-load`
- The current working directory is where the script is.
- `${0:A}` turns into `/Users/user/.antigen/bundles/fribmendes/geometry/-antigen-load`
- `${0:A:h}` strips the `-antigen-load` resulting in `/Users/user/.antigen/bundles/fribmendes/geometry`

This would work with `flibbit=nothing; echo ${flibbit:Ah}` as well. Or just use `$PWD`.

However this doesn't work (and neither does `%N`) if the current working directory isn't set to the prompt directory and the `.zsh-theme` is loaded via `fpath` and `autoload -Uz` (the way Prezto does).

Specifically, with this debug code in the prompt:

``` zsh
echo "NARF 0 ${0}"
echo "NARF 0 ${0:A}"
echo "NARF 0 ${0:A:h}"

echo "NARF N ${(%):-%N}"
echo "NARF N ${${(%):-%N}:A}"
echo "NARF N ${${(%):-%N}:A:h}"

echo "NARF x ${(%):-%x}"
echo "NARF x ${${(%):-%x}:A}"
echo "NARF x ${${(%):-%x}:A:h}"
```

I get these results:

```
# Plain zshrc source
NARF PWD /home/fred
NARF 0 /home/fred/my-prompt-theme/prompt_myprompt_setup
NARF 0 /home/fred/my-prompt-theme/myprompt.zsh-theme
NARF 0 /home/fred/my-prompt-theme
NARF N /home/fred/my-prompt-theme/prompt_myprompt_setup
NARF N /home/fred/my-prompt-theme/myprompt.zsh-theme
NARF N /home/fred/my-prompt-theme
NARF x /home/fred/my-prompt-theme/prompt_myprompt_setup
NARF x /home/fred/my-prompt-theme/myprompt.zsh-theme
NARF x /home/fred/my-prompt-theme
```

```
# Antigen
NARF PWD /home/fred/my-prompt-theme
NARF 0 -antigen-load
NARF 0 /home/fred/my-prompt-theme/-antigen-load
NARF 0 /home/fred/my-prompt-theme
NARF N (eval)
NARF N /home/fred/my-prompt-theme/(eval)
NARF N /home/fred/my-prompt-theme
NARF x /home/fred/antigen/antigen.zsh
NARF x /home/fred/antigen/antigen.zsh
NARF x /home/fred/antigen
```

```
# Prezto
NARF PWD /home/fred
NARF 0 prompt_myprompt_setup
NARF 0 /home/fred/prompt_myprompt_setup
NARF 0 /home/fred
NARF N prompt_myprompt_setup
NARF N /home/fred/prompt_myprompt_setup
NARF N /home/fred
NARF x /home/fred/.zprezto/modules/prompt/functions/prompt_myprompt_setup
NARF x /home/fred/my-prompt-theme/myprompt.zsh-theme
NARF x /home/fred/my-prompt-theme
```

`%x` works the best for the other cases; only Antigen requires checking the current working directory.  I'm still in the process of testing other frameworks (e.g. OMZ).

**Comment by desyncr** [comment]
I see. I believe it should work properly on `develop` branch and from `v2.1.0` and above.

**Comment by docwhat** [comment]
W00T!  It is indeed fixed in the `develop` branch @desyncr!

```
# Antigen 'develop' branch
NARF 0 /home/fred/my-prompt-theme/myprompt.zsh-theme
NARF 0 /home/fred/my-prompt-theme/myprompt.zsh-theme
NARF 0 /home/fred/my-prompt-theme
NARF N /home/fred/my-prompt-theme/myprompt.zsh-theme
NARF N /home/fred/my-prompt-theme/myprompt.zsh-theme
NARF N /home/fred/my-prompt-theme
NARF x /home/fred/my-prompt-theme/myprompt.zsh-theme
NARF x /home/fred/my-prompt-theme/myprompt.zsh-theme
NARF x /home/fred/my-prompt-theme
```
