### ISSUE TITLE
Antigen asks for Github credentials when installing zsh-autosuggestion plugin

### ISSUE THREAD

**Issue by KristupasSavickas** [zsh-users/antigen#585]
OS : Ubuntu 16.04
Zsh version : 5.1.1
Antigen version: v2.0.2

My .zshrc file: https://github.com/KristupasSavickas/dotfiles/blob/master/.zshrc

Using this configuration antigen asks for Github credentials during zsh-autosuggestion installation. For example, running `antigen reset` and restarting the terminal results in:
```
Installing zsh-users/zsh-autosuggestion@master... Username for 'https://github.com':
```
Entering the creditentials results in:
```
Installing zsh-users/zsh-autosuggestion@master... Username for 'https://github.com': xxx@xxx.com
Password for 'xxx@xxx.com@github.com': 
Error! Activate logging and try again.
```

Running `antigen purge` on everything installs all the plugins except zsh-autosuggestion like before.

**Comment by KristupasSavickas** [comment]
This was an issue with my .zshrc, I mistyped zsh-autosuggestions

**Comment by desyncr** [comment]
This should not happen with git v2.3 and above (see https://github.com/zsh-users/antigen/commit/e7d6710a75a767f4522c2d23a2f1789d4596af95).
Also https://github.com/zsh-users/antigen/wiki/Troubleshooting#asked-for-github-user-and-password-when-installing-bundles.
