### ISSUE TITLE
Zsh load error

### ISSUE THREAD

**Issue by saviour123** [zsh-users/antigen#586]
What is likely to cause this error for me:
`/home/sav/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git/plugins/npm/npm.plugin.zsh:5: permission denied: /npm_completion
ls: cannot access '/home/sav/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git/plugins/ipython': No such file or directory
ls: cannot access '/home/sav/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git/plugins/ipython': No such file or directory
ls: cannot access '/home/sav/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git/plugins/ipython': No such file or directory
`

**Comment by desyncr** [comment]
Mmmm seems to be something with this plugin. Try using antigen from develop.

Best regards
