### ISSUE TITLE
ANTIGEN_CACHE=false writes false and false.zwc files

### ISSUE THREAD

**Issue by nisaea** [zsh-users/antigen#590]
Hello,

Since I'm having huge problems with themes (only apply on the first zsh launched after an `antigen reset` and disappears in the subsequent instances,` ZSH_THEME` is always empty), I wanted to disable the caching altogether.

Following the documentation and helpful comments on other issues, I added `ANTIGEN_CACHE=false` in my .zshrc right before sourcing antigen. But surprisingly, it doesn't seem to stop the caching, it now writes `false` and `false.zwc` files wherever I open a terminal.

This doesn't look like the expected behavior, did I miss anything here?

```
$ antigen version           
Antigen v2.2.1 (1d212d1)
No extensions loaded.
```
My .zshrc:

```
ANTIGEN_CACHE=false
autoload antigen
source ~/.dotfiles/antigen/antigen.zsh
antigen use oh-my-zsh
antigen bundle arialdomartini/oh-my-git
antigen bundle git
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle colored-man-pages
BULLETTRAIN_PROMPT_ORDER=(
	time
	status
	custom
	context
	dir
	perl
	ruby
	virtualenv 
	aws
	go
	elixir
	git
	hg
	cmd_exec_time
)
antigen theme https://github.com/caiogondim/bullet-train-oh-my-zsh-theme bullet-train
antigen apply
```

PS: Thanks for the awesome work

**Comment by desyncr** [comment]
Thanks for reporting. I'll take a look at the issue (there is an issue being fixed with this configuration) and I'll release it as `2.2.2`.

**Comment by nisaea** [comment]
That's awesome, thanks! \o/

Should I open an issue for the original problem I faced or is it something that has already been fixed and I missed the info?

**Comment by yahyavi** [comment]
Same issue with fonts not working properly with caching, any way to fix this till the next release?

**Comment by desyncr** [comment]
@yahyavi Not unfortunately. But you can jump onto `develop` which has a fix right now. It's ready for `2.2.2`.
