### ISSUE TITLE
ANTIGEN_COMPDUMPFILE - not respected

### ISSUE THREAD

**Issue by cstockton** [zsh-users/antigen#591]
I can't seem to find a way to write the two .zcompdump{-host-ver} files elsewhere. It seems that  ANTIGEN_COMPDUMPFILE has no effect, was this feature disabled? If so how do I prevent this behavior or disable caching all together?

Edit: To clarify I've tried both versions as stated in the wiki: Both ANTIGEN_COMPDUMP and ANTIGEN_COMPDUMPFILE. I'm also certain both are exported, my .zshrc I've reduced to a single "source" call to "oh-my-zsh.sh" and nothing else.

```zsh
export ANTIGEN_COMPDUMP=/one/dot/zsh/.zcompdump
export ANTIGEN_COMPDUMPFILE=/one/dot/zsh/.zcompdump

plugins=(git)

source $ZSH/oh-my-zsh.sh
```

**Comment by dotwaffle** [comment]
Why are you calling `oh-my-zsh.sh`? Are you not calling `antigen apply` etc anywhere?

**Comment by cstockton** [comment]
At the time I wrote this I was just giving a default installation of "oh-my-zsh" a shot, which seems to include all of this "antigen" stuff. I noticed it was creating two files in my home directory, I didn't like this behavior so I googled how to fix it. This led me to the [wiki](https://github.com/zsh-users/antigen/wiki/Cookbook#configure-compdump-location) for this project, which did not work. It says:

```bash
Use ANTIGEN_COMPDUMPFILE to configure zsh compdump file location:

.zshrc:

export ANTIGEN_COMPDUMPFILE=/path/to/location/.zcompdump
Note: On Antigen v2 and above this configuration is ANTIGEN_COMPDUMP.
```

As for why I am calling oh-my-zsh.sh, that was what the installer.. installed. Rather than pasting the entire zsh file the installer put on my machine here- I posted the relevant details. That said the question was simply: **I can't seem to find a way to write the two .zcompdump{-host-ver} files elsewhere.** - Is antigen apply the answer to that question?

Feel free to close this issue out, I no longer need resolution. Thanks for the response.

**Comment by dotwaffle** [comment]
I'm not the maintainer, I just happened to be scanning issues before I submitted my own ;)

As I understand it, antigen and oh-my-zsh are different ways of doing the same thing. You can tell antigen to install various packages from within oh-my-zsh, rather than installing it as a whole. So, you'd say something like:

```
antigen use oh-my-zsh  # gets oh-my-zsh, but doesn't install it
antigen bundle git  # gets the git module from oh-my-zsh
antigen apply  # installs any bundles you've specified
```

If you just want all of oh-my-zsh, I think you just use oh-my-zsh. This is more of a pick-and-choose method, like Debian's apt, or OSX's homebrew. Or at least, that's how I see it.

To address your concern, I think the .zcompdump files are being installed by oh-my-zsh, it's not antigen. You'll have to look at oh-my-zsh to see how to rename / manage those.

**Comment by desyncr** [comment]
@cstockton As @dotwaffle put it very nicely. It seems it comes from oh-my-zsh configuration rather than Antigen's.

**Comment by cstockton** [comment]
I see, maybe the wiki that states it's part of [this project](https://github.com/zsh-users/antigen/wiki/Cookbook#configure-compdump-location) just needs updated then. Thanks for the response.

**Comment by desyncr** [comment]
The Antigen configuration variables are fine and the wiki explain them correctly. What is happening is that `source $ZSH/oh-my-zsh.sh` does uses it's own configuration `ZSH_COMPDUMP`.

You should not source oh-my-zsh when using Antigen, use instead `antigen use oh-my-zsh`.

**Comment by cstockton** [comment]
Okay sweet, if I ever give ZSH a try again I at least know how to fix that, thanks a lot.
