### ISSUE TITLE
Error from  OMZ bundle

### ISSUE THREAD

**Issue by igorvisi** [zsh-users/antigen#593]
.antigen/bundles/robbyrussell/oh-my-zsh/plugins/common-aliases/common-aliases.plugin.zsh:55: command not found: is-at-least
-antigen-load:popd:41: directory stack empty

**Comment by desyncr** [comment]
Which is your zsh version?

```
zsh --version

```

**Comment by igorvisi** [comment]
zsh 5.4.2

**Comment by scinos** [comment]
Same error with `zsh 5.2 (x86_64-apple-darwin16.0)`

**Comment by desyncr** [comment]
Should be enough with `autoload -U is-at-least` before loading antigen.

**Comment by dodoru** [comment]
Are you running it from bash? You should just run zsh and it will load the zshrc file itself.
