### ISSUE TITLE
`cache-gen`: is it meant to be run?

### ISSUE THREAD

**Issue by sohocoke** [zsh-users/antigen#595]
I'm finding all the antigen setup in my `.zshrc` is slowing down launch of new shells a little too much, and looking into how I can go all-out on using bundles, and still have a zippy shell.

Documentation suggests that `cache-gen` is done automatically as of v2.x, so presumably there's not benefit to running `antigen cache-gen`. Is it expected that if run, it will break antigen initialisation in .zshrc? Because that's what seems to be happening at the moment

Would very much appreciate some clarification, and any suggestion to speed up loading of bundles.

**Comment by sohocoke** [comment]
from https://github.com/zsh-users/antigen/wiki/Cookbook:
```
Static bundle loading

If you need to load Antigen faster you may load bundles statically from cache. This way you can avoid loading and running Antigen each time you shell starts.

Note: This will be unnecessary for 2.x (current develop) as this will be performed by Antigen itself.
```

I took this to mean that the caching is performed automatically, but I guess it was saying that the cache is used automatically without polluting .zshrc with a conditional, once it's generated with `cache-gen`.

**Comment by desyncr** [comment]
@sohocoke Cache is generated automatically unless configured not to do so, with `ANTIGEN_CACHE` configuration variable, see [here](https://github.com/zsh-users/antigen/wiki/Configuration#customizations). No need to use `cache-gen` manually.

**Comment by sohocoke** [comment]
@desyncr So do new `antigen bundle` commands added in the startup files expire the cache so the cache is automatically kept up-to-date?

**Comment by desyncr** [comment]
@sohocoke Antigen auto-expire cache when it detects changes in any config files (take a look at [here](https://github.com/zsh-users/antigen/wiki/Configuration#optimizations) - `$ANTIGEN_CHECK_FILES`).

Currently in `develop` it automatically check changes in `~/.zshrc` and tries to detect where Antigen is configured (antigen use, antigen bundle, antigen apply). You may configure it with `ANTIGEN_CHECK_FILES` like this:

    typeset -a ANTIGEN_CHECK_FILES;
    ANTIGEN_CHECK_FILES=(/path/to/.antigenrc /path/to/.zshrc /path/to/other)
