### ISSUE TITLE
Antigen disable custom autocompletion

### ISSUE THREAD

**Issue by Crandel** [zsh-users/antigen#597]
I create a function, that cd to my projects directory. I try to create auto-completion for this function
```
projects_folder="/opt/work/projects/"
function pr () {
  cd $projects_folder
  if [ ! -z $1 ]; then
    cd $1
  fi
}
compdef "_path_files -W $projects_folder -/ && return 0 || return 1" pr
```

When I disable 
`source ~/antigen.zsh` - everything works fine. I try to run `antigen reset` and delete .zcompdump. Nothing helps
My full [.zshrc config](https://github.com/Crandel/home/blob/master/.zshrc)

**Comment by mrmark** [comment]
Ah, this must have happened to me as well.  I had a completion function for a custom program and it suddenly stopped working.  Could never figure out the source.  Had to convert it into a ZSH plugin and load it via Antigen for it to start working again.

Would love to see this restored!

**Comment by Crandel** [comment]
I commented `antigen apply` in my *~/.zshrc* and everything works fine

**Comment by mrmark** [comment]
Huh, that doesn't seem like a solution, thought you needed the apply call?

**Comment by desyncr** [comment]
Hey there @Crandel, @mrmark Sorry for the delay in my response.

Regarding the original issue. Be sure to put `antigen apply` at the end of any `compdef`. Ex:

```
# autoload compinit && compinit

compdef <...> # custom compdef

...

antigen use <...>
antigen bundle <...>
antigen apply
```

Before trying out these changes remember to `antigen reset` in order to reset caching and compdefs.

**Comment by mrmark** [comment]
Thanks for the reply, if I add `autoload compinit && compinit` and then my `compdef` prior to `antigen` use, it does work.  Thank you!

**Comment by Crandel** [comment]
@desyncr Unfortunately your solution doesn\`t work for me. 

```
autoload -Uz compinit
compinit

antigen_source="$HOME/antigen.zsh"

# Custom compdef
project_folders="/opt/work/projects/"
function prj () {
  cd $project_folders
  if [ ! -z $1 ]; then
    cd $1
  fi
}
compdef "_path_files -W $project_folders -/ && return 0 || return 1" prj

backup_dir="/opt/work/backup"
function backup () {
  cd $backup_dir
  if [ ! -z $1 ]; then
    cd $1
  fi
}
compdef "_path_files -W $backup_dir -/ && return 0 || return 1" backup
. $antigen_source
antigen use oh-my-zsh
antigen bundle git
antigen bundle pip
antigen bundle command-not-found
antigen bundle shrink-path
antigen bundle mvn
antigen bundle sbt
antigen bundle scala
antigen bundle cargo
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-history-substring-search
antigen bundle zsh-users/zsh-syntax-highlighting
antigen apply
```

Still don\`t have autocomplete for **prj** and **backup** functions. 
`antigen reset && rm ~/.zcompdump` was done before testing

**Comment by desyncr** [comment]
@Crandel Hey there, tried your snippet with the following antigen and zsh version and it worked (it did autocompleted `prj` and `backup` commands)

```
dc@machine:~% antigen version
antigen version
Antigen v2.0.2
dc@machine:~% zsh --version
zsh --version
zsh 5.2 (x86_64-ubuntu-linux-gnu)
dc@machine:~% uname -a
uname -a
Linux machine 4.10.0-33-generic #37-Ubuntu SMP Fri Aug 11 10:55:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Two things you can try:

- Move `. $antigen_source` line right after `antigen_source="$HOME/antigen.zsh"` line
- Disable caching with `ANTIGEN_CACHE=false` (put this before sourcing Antigen)
