### ISSUE TITLE
ANTIGEN_RSRC not respected from outside script

### ISSUE THREAD

**Issue by dotwaffle** [zsh-users/antigen#598]
In `bin/antigen.zsh` line 13, ANTIGEN_RSRC is over-written by ADOTDIR if that is set, which clobbers my attempt to set ANTIGEN_RSRC before launching antigen.

I have my dotfiles accessible via both my OSX laptop and my servers. As OSX, Linux, and FreeBSD all store the home directory in different places, there's a problem here because it drops a `.resources` file in ADOTDIR.

I've mitigated all the other dropped files by using:

```
ADOTDIR="$HOME/.zsh/antigen"
ANTIGEN_HOSTS="$ADOTDIR/hosts/$HOSTNAME"
[[ ! -d "$ANTIGEN_HOSTS" ]] && mkdir -p "$ANTIGEN_HOSTS"
ANTIGEN_CACHE="$ANTIGEN_HOSTS/init.zsh"
ANTIGEN_COMPDUMP="$ANTIGEN_HOSTS/.zcompdump"
ANTIGEN_DEBUG_LOG="$ANTIGEN_HOSTS/debug.log"
source ~/.zsh/antigen-src/antigen.zsh
```

However, when .resources is dropped, it contains the expanded $HOME parameter, producing:

```
15:49:35 [dotwaffle@engelbert:~/.zsh] % cat antigen/.resources
/home/dotwaffle/.dotfiles/common/.zsh/antigen-src/bin/antigen.zsh
```

When I then login on my laptop, I get an error like:

```
-antigen-cache-generate:zcompile:54: can't write zwc file: /home/dotwaffle/.dotfiles/common/.zsh/antigen-src/bin/antigen.zsh.zwc
```

If we could override the ANSIBLE_RSRC variable from outside the script, that should fix the issue.

**Comment by desyncr** [comment]
It should be solved in `develop` and next release `2.2.2`.
