### ISSUE TITLE
Antigen Caching Issues with powerlevel9k for font Glyphs

### ISSUE THREAD

**Issue by yahyavi** [zsh-users/antigen#601]
Hi,

I am having issues with Antigen caching. If the caching is enabled the glyphs and icons do not show up properly:

without caching:
<img width="450" alt="screen shot 2017-10-30 at 11 20 53 pm" src="https://user-images.githubusercontent.com/1531957/32210227-bcabae46-bdc9-11e7-9446-67e23b0a103a.png">

with caching:
<img width="388" alt="screen shot 2017-10-30 at 11 22 00 pm" src="https://user-images.githubusercontent.com/1531957/32210229-bd03a786-bdc9-11e7-97ab-2200f8639dc1.png">

It is not a font or terminal problem but clearly comes from cahing. With caching disabled the terminal startup is quite slow.

A simplified .zshrc is as follows:

```bash
POWERLEVEL9K_INSTALLATION_PATH="~/.antigen/bundles/bhilburn/powerlevel9k/"
POWERLEVEL9K_MODE="awesome-patched"
POWERLEVEL9K_ALWAYS_SHOW_CONTEXT=true
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=1
POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=3
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(status os_icon context dir dir_writable)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(vcs root_indicator background_jobs command_execution_time history)

antigen use oh-my-zsh
# ...
antigen bundle git
antigen bundle git-extra
antigen bundle github
# ...
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-history-substring-search
antigen bundle zsh-users/zsh-syntax-highlighting

antigen theme bhilburn/powerlevel9k powerlevel9k

# Tell Antigen that you're done.
antigen apply
```

**Comment by cvuorinen** [comment]
Same problem here since updated to antigen v2
