### ISSUE TITLE
some problems with antigen installation process

### ISSUE THREAD

**Issue by GiovanniSM20** [zsh-users/antigen#604]
I had some problems trying to install antigen for cURL, but in another way, it worked out better!

```
mkdir ~/.zsh-antigen
cd ~/.zsh-antigen
git init .
git submodule add https://github.com/zsh-users/antigen.git antigen
ZSHA_BASE=$HOME/.zsh-antigen
source $ZSHA_BASE/antigen/antigen.zsh
```

**Comment by desyncr** [comment]
Added it to the Cookbook wiki section. See [here](https://github.com/zsh-users/antigen/wiki/Cookbook#adding-antigen-to-your-dotfiles).

Thanks a lot!
