### ISSUE TITLE
cd -q creates errors

### ISSUE THREAD

**Issue by bin101** [zsh-users/antigen#617]
I dont know on which os -q is an option for the cd command but on Linux/Posix systems it creates errors, e.g. if I use antigen update.

**Comment by desyncr** [comment]
Check `man zshbuiltins`. `cd` supports `-q` flag:

    If the -q (quiet) option is specified, the hook  function  chpwd
    and  the  functions in the array chpwd_functions are not called.
    This is useful for calls to cd that do not change  the  environ‐
    ment seen by an interactive user.

**Comment by bin101** [comment]
Do I need a special option to enable the builtins? Because if I run a "cd -q *dir*" or try antigen update I only get following error: cd:cd: string not in pwd: -q

**Comment by bin101** [comment]
nvm did an overload for cd years ago to show the content of the entered dir. I am sry for opening this issue...

**Comment by desyncr** [comment]
@bin101 No problem! :+1: We have a pending issue with aliased commands, in order for this not to happen. I'll review that.

**Comment by desyncr** [comment]
Antigen should work fine with an aliased `cd` command.

**Comment by bin101** [comment]
I didnt used an alias I wrote a function to overload cd:
```shell
# ENTER AND LIST DIRECTORY{{{
    function cd() { builtin cd -- "$@" && { [ "$PS1" = "" ] || ls -hrt --color --group-directories-first; }; }
#}}}
```

I dont know if it is possible to get antigen working with this.

**Comment by desyncr** [comment]
@bin101 I don't think it can be done. I tried doing the following:

```

command cd ...

```

But it doesn't seems to work. I'll keep an eye on it though.
