### ISSUE TITLE
Outdated version 2.0.2 in README

### ISSUE THREAD

**Issue by adambro** [zsh-users/antigen#621]
The URL `git.io/antigen` points to `master` branch that has got version `Antigen v2.0.2 (5599e4a)` still.

**Comment by adambro** [comment]
FYI: with version 2.0.2 the git plugin from oh-my-zsh completion for git commands broke some time ago (see error below), but with 2.2.2 is works well:

```
_git:58: _git_commands: function definition file not found
```

**Comment by desyncr** [comment]
Hi @adambro Latest stable is 2.0.2, which is the one pointed by `git.io/antigen`, to get the nightly/develop you can use `git.io/antigen-nightly`.

I've to release 2.2.1 or 2.2.2 as stable in a few days.

**Comment by adambro** [comment]
OK, thanks for quick response. I have no idea idea about the versioning, but take into consideration that 2.2.2 fixed my problem with git plugin from OMZ. I've tried that on Ubuntu 17.04 box, because it worked well all the time with antergos-git AUR package.

Thanks a lot for your great work, Antigen is totally awesome!
