### ISSUE TITLE
Antigen doesn't apply theme from .zshrc

### ISSUE THREAD

**Issue by HazardDev** [zsh-users/antigen#624]
My zshrc

```
export NVM_DIR="$HOME/.nvm"

source "$HOME/.zsh-plugins/antigen.zsh"
# Load the oh-my-zsh's library
antigen use oh-my-zsh

antigen bundle git
antigen bundle ssh-agent

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions

# Load the theme
antigen bundle lukechilds/zsh-nvm

antigen theme kobayashi/sushi-theme

antigen apply
```

Running `antigen theme kobayashi/sushi-theme` after the fact works fine, and all the other plugins seem to be working too.

**Comment by desyncr** [comment]
Seems to work OK on `2.2.2`/develop.

**Comment by HazardDev** [comment]
I am running zsh version `5.4.2 (x86_64-apple-darwin16.7.0)`

and I just cloned antigen from git last night.

**Comment by desyncr** [comment]
Glad you got it working! Maybe it was an issue between versions :/
