### ISSUE TITLE
antigen-update() not loaded at start

### ISSUE THREAD

**Issue by ncihnegn** [zsh-users/antigen#651]
Description
-----------

After sourcing antigen.zsh, antigen-update() function is not loaded.

Steps to reproduce
------------------

Minimal steps to reproduce this behavior. Example:

    1 - Close all terminals
    2 - Open terminal
    3 - which antigen-update

Expected behavior:

 - It shows 'antigen-update not found'
 - Moving source antigen.zsh to .zprofile fixes the problem
 

## Software version

- 2.2.2
- 5.3 (x86_64-apple-darwin17.0)
- Darwin MacBook.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64

## Configuration

- empty .antigenrc
- https://gist.github.com/ncihnegn/1a542ef30dd37abc6fb20da32f65582b

## More information

Screenshot or any other information you may find relevant to troubleshoot the issue.

**Comment by desyncr** [comment]
The reason this function among others are not available is those functions are lazy loaded at run time.  With the `antigen` wrapper function.

You should not use any `antigen-` function, unless you're somehow working with Antigens internals.

You may use `antigen update` instead, and check for antigen command (`which antigen`).
