### ISSUE TITLE
antigen can't apply the same theme again

### ISSUE THREAD

**Issue by ncihnegn** [zsh-users/antigen#652]
Description
-----------

After applying theme in .zshrc, sourcing .zshrc again will hang the shell.

Steps to reproduce
------------------

Minimal steps to reproduce this behavior. Example:

    1 - Open terminal
    2 - Source .zshrc

Expected behavior:
Assuming the theme is refined in .zshrc,
 ~
❯ antigen theme refined
Seems robbyrussell/oh-my-zsh is already installed!

~
**(Here not showing the prompt anymore)**
 

## Software version

- 2.2.2
- 5.3 (x86_64-apple-darwin17.0)
- Darwin MacBook.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64

## Configuration

- empty .antigenrc
- https://gist.github.com/ncihnegn/1a542ef30dd37abc6fb20da32f65582b

## More information

Screenshot or any other information you may find relevant to troubleshoot the issue.

**Comment by desyncr** [comment]
Can you check this out with 2.2.3? We have worked on similar issue which should be fixed on 2.2.3.

**Comment by ncihnegn** [comment]
I just checked, at least the develop version works.
