### ISSUE TITLE
Problems with antigen-cache-generate

### ISSUE THREAD

**Issue by sambadevi** [zsh-users/antigen#655]
Description
-----------

Whenever I uncomment my .zshenv settings I get an error on a new terminal

```
-antigen-cache-generate:4: parse error near `)'
-antigen-cache-generate:zcompile:58: can't read file: /Users/tim/.antigen/init.zsh
/Users/tim/.antigen/init.zsh:1: bad pattern: ^[[38
```

Steps to reproduce
------------------

Minimal steps to reproduce this behavior.

    1 - Open terminal
    2 - aforementioned error is displayed

Expected behavior:

    - No error messages visible and zsh is loading with the configured plugins
 

## Software version

- `antigen version` -- 2.2.2
- `zsh --version` -- 5.4.2
- `uname -a` -- `Darwin Tims-MBP.fritz.box 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64`

## Configuration

- gist of `.antigenrc` --> I did not create a .antigenrc
- [gist of `.zshrc`](https://gist.github.com/sambadevi/8dbacad73db9e64092e5ad54632fb956)
- [gist of `.zshenv`](https://gist.github.com/sambadevi/8ec7e7226d0607ad014c4c3bb2f0eaba)

## More information

I found a workaround in commenting my whole .zshenv, doing `rm -rf .antigen` and starting the shell again for installing everything, but I suppose the mentioned errors are not intended?

**Comment by tmjoen** [comment]
For anyone else experiencing this:

It's because of the `cat` override somewhere in your zsh config.

I had mine in $dotfiles/zsh/lib/aliases.zsh

```zsh
# `cat` with beautiful colors. Requires Pygments installed.
if command-exists pygmentize; then
  alias cat='pygmentize -O style=friendly -f console256 -g'
fi
```

Just comment out the alias, delete `.antigen` and start shell.

**Comment by sambadevi** [comment]
I was using the exact same alias for `cat`

Maybe antigen should use `/bin/cat` instead

**Comment by codingwesley** [comment]
I have same issues，error message is `-antigen-cache-generate:compile:65: bad option: -s`
and I exec cmd: `rm -rf ~/.antigen` resolve it.

**Comment by bencoullie** [comment]
Yup, removing (or rather renaming) my `cat` alias resolved this 👍
