### ISSUE TITLE
a more line write

### ISSUE THREAD

**Issue by yaserrahimi** [zsh-users/antigen#663]
I install antigen and i have a problem 
terminal write a more line after any command
you are can see it in screenshot 

antigen version      
Antigen develop (d1dd78b)
Revision date: 2018-01-15 14:37:21 -0300

zsh --version 
zsh 5.4.2 (x86_64-ubuntu-linux-gnu)

uname -a
Linux yaspc 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

my zshrc 
https://gist.github.com/yaserrahimi/7b8dac11c743d7ee17bbb2fbcb95c7c6

![screenshot from 2018-05-23 12-54-17](https://user-images.githubusercontent.com/19384196/40413088-39688de4-5e8a-11e8-9bb3-ffe728e04a87.png)

**Comment by lwshang** [comment]
That's the behavior of pure prompt. It's not an issue with Antigen.
