### ISSUE TITLE
Provide documentation for removing oh-my-zsh and installing Antigen

### ISSUE THREAD

**Issue by piggyslasher** [zsh-users/antigen#667]
Description
-----------

Currently the Wiki's are a little vague in showing how a user can migrate from oh-my-zsh cleanly into antigen, completely removing the existing instance of oh-my-zsh.

Steps to reproduce
------------------

Wiki pages don't take this into account in the [quick start](https://github.com/zsh-users/antigen/wiki/Quick-start) or [installation](https://github.com/zsh-users/antigen/wiki/Installation)

Expected behavior:

  - Should mention how to remove zsh or cleanly port over to antigen
 

## Software version

Doesn't apply

##
I am currently documenting the how I'm migrating. Will be happy to add to the WiKi.

**Comment by melMass** [comment]
It should be as straightforward as removing the $ZSH env and ~/.oh-my-zsh folder. Nothing more...

**Comment by piggyslasher** [comment]
Yup. And I moved to antibody. Easier to debug what slowing the terminal down.

**Comment by architchandra** [comment]
Sorry, I'm a noob and couldn't understand how to remove the $ZSH env. Is there any guide that I can refer to for this?
