### ISSUE TITLE
Permission denied when zsh loads. No modules loading.

### ISSUE THREAD

**Issue by jsquardo** [zsh-users/antigen#677]
Description
-----------

Getting this error when loading shell:

`/Users/johnny/.zshrc:7: permission denied: /Users/johnny/antigen.zsh
/Users/johnny/.zshrc:10: command not found: antigen
/Users/johnny/.zshrc:16: command not found: antigen
/Users/johnny/.zshrc:17: command not found: antigen
/Users/johnny/.zshrc:18: command not found: antigen
/Users/johnny/.zshrc:19: command not found: antigen
/Users/johnny/.zshrc:20: command not found: antigen
/Users/johnny/.zshrc:21: command not found: antigen
/Users/johnny/.zshrc:22: command not found: antigen
/Users/johnny/.zshrc:23: command not found: antigen
/Users/johnny/.zshrc:24: command not found: antigen
/Users/johnny/.zshrc:25: command not found: antigen
/Users/johnny/.zshrc:26: command not found: antigen
/Users/johnny/.zshrc:27: command not found: antigen
/Users/johnny/.zshrc:28: command not found: antigen
/Users/johnny/.zshrc:29: command not found: antigen
/Users/johnny/.zshrc:30: command not found: antigen
/Users/johnny/.zshrc:34: command not found: antigen
/Users/johnny/.zshrc:35: command not found: antigen
/Users/johnny/.zshrc:38: command not found: antigen
/Users/johnny/.zshrc:41: command not found: antigen`

Steps to reproduce
------------------

Minimal steps to reproduce this behavior. Example:

This is my .zshrc setup:

`if [ -x /usr/libexec/path_helper ]; then
     eval `/usr/libexec/path_helper -s`
fi

~/antigen.zsh

antigen use oh-my-zsh

autoload -U promptinit; prompt init
prompt pure

1 antigen bundle git
2 antigen bundle heroku
3 antigen bundle pip
# have more here up to 29...
29 antigen bundle zsh-users/zsh-syntax-highlighting
30 antigen bundle zsh-users/zsh-history-substring-search ./zsh-history-substring
31
32 # NVM bundle
33 export NVM_LAZY_LOAD=true
34 antigen bundle lukechilds/zsh-nvm
35 antigen bundle Sparragus/zsh-auto-nvm-use
36
37 # Syntax highlighting bundle.
38 antigen bundle zsh-users/zsh-syntax-highlighting
39
40 # Tell Antigen that you're done.
41 antigen apply
42
43 # Setup zsh-autosuggestions
44 source "$HOME/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh"
45
46 # Load custom aliases
47 [[ -s "$HOME/.bash_aliases" ]] && source "$HOME/.bash_aliases"
48
49 # Load NVM
50 export NVM_DIR="$(realpath $HOME/.nvm)"
51 [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
.zshrc (37,7) zsh unix                   Alt-g: show bindings, CtrlG: open help
> quit
/Users/johnny/.zshrc:26: command not found: antigen
/Users/johnny/.zshrc:27: command not found: antigen
/Users/johnny/.zshrc:28: command not found: antigen
71 export CLICOLORS=YES
72 export LSCOLORS="Gxfxcxdxbxegedabagacad"
73 zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
74 zstyle ':completion:*' list-colors ''
75 zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the characte
76 zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}'
77 zstyle ':completion:*' menu select=long
78 zstyle ':completion:*' select-prompt %SScrolling active: current selection at
79 zstyle ':completion:*' use-compctl false
80 zstyle ':completion:*' verbose true
81
82 zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;
83 zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cm
84
85 #autocomplete
86 fpath=(/usr/local/share/zsh-completions $fpath)
87

.zshrc (1,1) zsh unix                    Alt-g: show bindings, CtrlG: open help
`

 

## Configuration

- `.antigenrc`
- `.zshrc`

## More information

Screenshot or any other information you may find relevant to troubleshoot the issue.

**Comment by HemalR** [comment]
Did you ever find a fix to this? I've run into the same issue :/

**Comment by dnglchlk** [comment]
I experienced this yesterday and found a fix by deleting antigen.zsh and getting it again from a non-zsh shell
