### ISSUE TITLE
A Newbies Questions

### ISSUE THREAD

**Issue by SonOfDiablo** [zsh-users/antigen#694]
The readme said to open an issue to discuss _Anything_ about Antigen.   

> Any comments/suggestions/feedback is truly welcome. Please say hello to us on Gitter. Or open an issue to discuss something (anything!) about the project ;).
   
So I'm gonna give this a shot before diving in head first.    
   
I have been using Oh-My-zsh and just now learned about Antigen.    
I'm also fairly new to zsh in general so I'm not quite sure how the configuration work, so my question is as follows:   
   
In my [.zshrc](https://gist.github.com/SonOfDiablo/180c71314149a611b3185e03aad4dc97) I have a few things configured so far.   
So when I install Antigen I should only have to replace the following lines with the Antigen commands as explained [here](https://github.com/zsh-users/antigen/wiki/Commands):   

- export ZSH="/home/sonofdiablo/.oh-my-zsh"
- ZSH_THEME="sod"
- plugins=(...)
- source $ZSH/oh-my-zsh.sh   
   
The rest should be left as is.    
Am I understanding this correctly?

**Comment by benzkji** [comment]
probably yes!

**Comment by SonOfDiablo** [comment]
> probably yes!

Totally forgot I opened an issue here.
I tried it out a few days ago and it seemed to work without problems.

Thanks for the reply though appreciate it :)
