### ISSUE TITLE
Uninstall instructions?

### ISSUE THREAD

**Issue by m-graf** [zsh-users/antigen#696]
Description
-----------

Is there documentation for uninstallation instructions? Thanks.

**Comment by benzkji** [comment]
just clean up your .zshrc? and maybe sudo apt remove antige, if you used apt to install...not an expert, though...

**Comment by m-graf** [comment]
> just clean up your .zshrc? and maybe sudo apt remove antige, if you used apt to install...not an expert, though...

I don't see how cleaning up `.zshrc` and uninstalling antigen really have anything to do with each other. I understand removing the references to antigen in `zshrc` will no longer *reference* the code, but I'd like to remove it entirely.

**Comment by benzkji** [comment]
hm. I see. Don't really know what happens when running the install `curl`...so your issue sounds legit. Removing antigen from .zshrc prevents loading anything antigen related. So you would probably just need to find the .zsh scripts, and delete them.

**Comment by m-graf** [comment]
Anyone? BUMP

**Comment by dunklesToast** [comment]
Curl just downloads the script. Remove the references from `.zshrc`, remove the downloaded file and clean up the plugins folder. Thats it.
