### ISSUE TITLE
Getting syntax error when sourcing antigen (ZSHRC) on WSL Ubuntu

### ISSUE THREAD

**Issue by ridhwaans** [zsh-users/antigen#697]
Description
-----------

Small paragraph to describe the issue/bug.

Using the latest version of Windows 10, Windows Subsystem for Linux, and Ubuntu downloaded from the Microsoft Store in WSL
Also using the shell `C:\\Windows\\System32\\wsl.exe`

Steps to reproduce
------------------

Minimal steps to reproduce this behavior. Example:

Getting syntax error near unexpected token `fi'
Full command log is
```
user@DESKTOP-DL1NO2L:~$ source ~/.zshrc 
-bash: /usr/libexec/java_home: No such file or directory
zmodload: command not found
autoload: command not found
-bash: /home/user/.zsh/bundle/bin/antigen.zsh: line 30: syntax error near unexpected token `fi'
-bash: /home/user/.zsh/bundle/bin/antigen.zsh: line 30: `      fi'
antigen: command not found
antigen: command not found
antigen: command not found
antigen: command not found
```
Expected behavior:

What should be happening is the command `source ~/.zshrc` should run succesfully and update the CLI bar and theme with the reloaded plugins (i.e. powerline bar credit oh-my-zsh)
 

## Software version

latest antigen, 'develop' branch (`origin  git@github.com:zsh-users/antigen.git`)

`Linux DESKTOP-DL1NO2L 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux`

## Configuration

`.zshrc` snippet
```
source $HOME/.zsh/bundle/bin/antigen.zsh

antigen use oh-my-zsh # Load the oh-my-zsh's library.

# Bundles from oh-my-zsh.
antigen bundle git
# Color schemes
antigen theme agnoster

antigen apply # Tell antigen that you're done.
```
## More information

Screenshot or any other information you may find relevant to troubleshoot the issue.

**Comment by benzkji** [comment]
dont know much about WSL. but to me, it looks like you are not using zsh (but bash, that complains about the syntax that probably only works in zsh...), when sourcing .zshrc. You must make sure your are using the right shell, first...for testing, you can just call `zsh` first, this would also load your .zshrc...

**Comment by ridhwaans** [comment]
Temp solution, add `bash -c zsh` to the top of `~/.bashrc`
