### ISSUE TITLE
tmux won't read zsh startup files when I have `antigen use prezto`

### ISSUE THREAD

**Issue by smackesey** [zsh-users/antigen#76]
When I open up a (non-tmux) shell, and launch tmux from it, normally tmux will open and execute my shell startup files as normal. However, when I have `antigen use prezto` in my zshrc, when I launch tmux no startup files are executed. `$SHELL` brings me to this screen:

>smackesey% $SHELL
This is the Z Shell configuration function for new users,
zsh-newuser-install.
You are seeing this message because you have no zsh startup files
(the files .zshenv, .zprofile, .zshrc, .zlogin in the directory
~/.antigen/repos/).  This function can help you with a few settings that should
make your use of the shell easier.

>You can:

>(q)  Quit and do nothing.  The function will be run again next time.

>(0)  Exit, creating the file ~/.antigen/repos//.zshrc containing just a comment.
     That will prevent this function being run again.

>(1)  Continue to the main menu.

>--- Type one of the keys in parentheses ---

Notice it's looking for startup files **~/.antigen/repos**. I'm not sure whether I just don't understand something or this is a bug, but I didn't know where else to post.  A temporary workaround is to symlink the startup files into ~/.antigen/repos.

**Comment by desyncr** [comment]
No updates since 2014. I'm closing this for now.
