### ISSUE TITLE
Release tags?

### ISSUE THREAD

**Issue by fladi** [zsh-users/antigen#80]
Are there any plans to publish a stable release? I'd like to provide antigen as a Debian package so people can easily install it and a release or a tag would make packaging a lot easier.

**Comment by fladi** [comment]
Any chances that we will see a new release tag? There have been quite a few additions since v1.

**Comment by HeroCC** [comment]
I think the best time for a v2 tag would be when #129 is complete, as it is a lot of code changes and will be a large update to antigen.
