### ISSUE TITLE
$fpath completion folders not processed

### ISSUE THREAD

**Issue by bedge** [zsh-users/antigen#85]
I have no idea whether this is an antigen thing of not, but I'm out of ideas.

I'm loading this in my ~/.zshrc (symlinked to ~/.antigen/zshrc) after running antigen-apply:

fpath=( "${fpath[@]}" /usr/local/share/zsh-completions /usr/local/share/zsh/site-functions )

None of the /usr/local/share/zsh-completions completions are being loaded. 

I do have an obscene amount of completers, but it should still work
%> echo $fpath | tr ' ' '\n'
/home/drat/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-arialdomartini-SLASH-oh-my-git.git//
/home/drat/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git/plugins/git-remote-branch
/home/drat/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git/plugins/ruby
/home/drat/.zsh-antigen/bundles/virtualenv
/home/drat/.zsh-antigen/bundles/stv
/home/drat/.zsh-antigen/bundles/git-completion
/home/drat/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-syntax-highlighting.git//
/home/drat/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-completions.git/src
/home/drat/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-history-substring-search.git//
/home/drat/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git/plugins/vagrant
/home/drat/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git/plugins/fabric
/home/drat/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git/plugins/sprunge
/home/drat/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git/plugins/vundle
/home/drat/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git/plugins/tmux
/home/drat/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git/plugins/history
/home/drat/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git/plugins/command-not-found
/home/drat/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-kennethreitz-SLASH-autoenv.git//
/home/drat/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git/plugins/bundler
/home/drat/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git/plugins/rake
/home/drat/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git/plugins/npm
/home/drat/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git/plugins/node
/home/drat/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git/plugins/python
/home/drat/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git/plugins/rsync
/home/drat/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git/plugins/pip
/home/drat/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git/plugins/git
/home/drat/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git/plugins/osx
/home/drat/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git/lib
/usr/share/zsh/site-functions
/usr/share/zsh/5.0.2/functions
/usr/local/share/zsh-completions
/usr/local/share/zsh/site-functions

Regardless of whether I put /usr/local/share/zsh-completions first or last in the fpath= statement, they are ignored.

Is there anything to assist in tracking what's being loaded on shell startup?

**Comment by desyncr** [comment]
No update since 2014. I'm closing this for now.
