### ISSUE TITLE
Random theme

### ISSUE THREAD

**Issue by DArtagan** [zsh-users/antigen#88]
Hello,
I'm beginning to use antigen and it's so nice to bring some portable sanity to oh-my-zsh and company.  After trying some things and looking at the source code, it looks like it's no longer possible to get a random theme on each terminal start.  This functionality may be out of the desired scope for Antigen, so I'd like to get a feel whether I should take the time to put together a pull request for it?  Also to note, the OMZ's random theme functionality may be changing soon - per https://github.com/robbyrussell/oh-my-zsh/pull/2902
Thoughts?

**Comment by beidi3340** [comment]
@sharat87 
just customize your favorite themes in the ~/.zshrc file in a random way and in the ~/.antigen file add this:
antigen theme random

for example here are my two files in my case.
***#My ~/.zshrc file***
```
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME=""
ZSH_THEME_RANDOM_CANDIDATES=("norm" "nebirhos" "ys" "kennethreitz" "bira" "junkfood" "gnzh")
plugins=(git cp screen colorize pass sudo)
source ${(q-)PWD}/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

source $ZSH/oh-my-zsh.sh
source $HOME/antigen.zsh
antigen init ~/.antigenrc
```
***My ~/.antigen file***
```
# Load oh-my-zsh library.
antigen use oh-my-zsh
# Load bundles from the default repo (oh-my-zsh).
antigen bundle git
antigen bundle command-not-found
antigen bundle docker
antigen bundle debian
antigen bundle adb
antigen bundle history
# Load bundles from external repos.
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting
# Select theme.
antigen theme random

# Tell Antigen that you're done.
antigen apply

```
