### ISSUE TITLE
completion for file args doesn't happen if I use `antigen apply`

### ISSUE THREAD

**Issue by matschaffer** [zsh-users/antigen#89]
I'm using `antigen bundles` to list a set of bundles, then I was calling `antigen apply` afterwards.

Not sure this is required since bundles still seem to load if I remove that call. And oddly enough it also makes completion for file name arguments work again.

To clarify, with this setup, I can tab-complete local file paths:

``` sh
source "$HOME/.antigen/antigen/antigen.zsh"

antigen bundles <<EOBUNDLES
  zsh-users/zsh-syntax-highlighting

  sindresorhus/pure

  matschaffer/zsh-matschaffer
EOBUNDLES
```

But if I add the apply step, I can't tab-complete local file paths:

``` sh
source "$HOME/.antigen/antigen/antigen.zsh"

antigen bundles <<EOBUNDLES
  zsh-users/zsh-syntax-highlighting

  sindresorhus/pure

  matschaffer/zsh-matschaffer
EOBUNDLES

antigen apply
```

Is this expected?

**Comment by clinta** [comment]
I want to reopen this because I'm seeing the same thing, but it's affecting ls and cd commands for me. I'm running antigen on zsh 5.0.6 on cygwin.

```
localhost% ls dotfiles                                       #Tab complete works
localhost% source antigen/antigen.zsh
localhost% ls dotfiles                                      #Tab complete still works
localhost% antigen apply
localhost% ls dot                                            #Tab complete doesn't work anymore
```

This is without any plugins loaded at all, just running apply breaks tab completion.

**Comment by clinta** [comment]
Nevermind, this was a cygwin issue, solved by doing this:

http://blog.en.edaro.net/2014/01/fix-broken-autocompletion-with-zsh-in.html
