### ISSUE TITLE
'selfupdate' failed even antigen is installed using git clone

### ISSUE THREAD

**Issue by wangyandong-ningxia** [zsh-users/antigen#99]
```
»  zsh --version                                                          
zsh 5.0.5 (i686-pc-linux-gnu)
-----
» zsh --version                                                             
zsh 5.0.5 (x86_64-apple-darwin14.0)
```
 I installed antigen using git clone. When running the antigen ```selfupdate``` command, it gives this error
```
Your copy of antigen doesn't appear to be a git clone. 
The 'selfupdate' command cannot work in this case.
```

**Comment by desyncr** [comment]
The `selfupdate` command basically executes a `git pull` on `$_ANTIGEN_INSTALL_DIR`. What's the value of that environment variable? Check that it matches the path where you cloned antigen.

Hope that helps!

**Comment by wangyandong-ningxia** [comment]
Actually _ANTIGEN_INSTALL_DIR is not available after antigen.sh is evaluate:
```
wangyandong@wangyandong-osx ~
» echo $_ANTIGEN_INSTALL_DIR                                                                                        1 ↵

wangyandong@wangyandong-osx ~
»
```

``` » cd $_ANTIGEN_INSTALL_DIR```  will navigate to the home directory.

**Comment by desyncr** [comment]
Of course, as `$_ANTIGEN_INSTALL_DIR` is a local variable on the `antigen` command. Thought you could debug `antigen.zsh` and check there the value of this variable.

**Comment by wangyandong-ningxia** [comment]
Thanks for your replay.

I add the debug line within the ```antigen-selfupdate``` function itself

```
antigen-selfupdate () {
    echo "==> $_ANTIGEN_INSTALL_DIR"
    ( cd $_ANTIGEN_INSTALL_DIR
        if [[ ! ( -d .git || -f .git ) ]]; then
            echo "Your copy of antigen doesn't appear to be a git clone. " \
                "The 'selfupdate' command cannot work in this case."
            return 1
        fi
...
```
and it still gives the same error
```
wangyandong@wangyandong-osx ~
» antigen selfupdate                                                                                                1 ↵
==>
Your copy of antigen doesn't appear to be a git clone.  The 'selfupdate' command cannot work in this case.
```

**Comment by desyncr** [comment]
It looks as if `$_ANTIGEN_INSTALL_DIR`  was empty. Do this: Add the following lines to `antigen.zsh`:

    echo $0
    echo $(dirname "$0")

After [this line](https://github.com/zsh-users/antigen/blob/master/antigen.zsh#L12). In my set up it prints:

    /home/<username>/.antigen//antigen.zsh
    /home/<username>/.antigen


Are you using tmux? It some times messes up with env variables.

**Comment by wangyandong-ningxia** [comment]
I'm not using tmux now.
```
echo $0
echo $(dirname "$0")
```
gives expected results
```
/Users/wangyandong/.antigen/antigen.zsh
/Users/wangyandong/.antigen
```

I think I've found the problem.  ```antigen.sh``` is sourced within a function I defined in my dotfiles. After moving the ```source /<path_to_antigen>/antigen.sh``` line out of the function, it works fine now.

Thank you.
